### ISSUE TITLE
Fix use of resource_filename() in templates.py.

### ISSUE THREAD

**Issue by weaverba137** [desihub/desisim#115]
templates.py contains several uses of `resource_filename()` such as this:

```python
        recombfile = resource_filename('desisim', os.path.join('..','..','data',
                                                               'recombination_lines.ecsv'))
        forbidfile = resource_filename('desisim', os.path.join('..','..','data',
                                                               'forbidden_lines.ecsv'))
        forbidmogfile = resource_filename('desisim', os.path.join('..','..','data',
                                                                  'forbidden_mogs.fits'))
```

This is abuse of `resource_filename()`.  This function is meant to find files *within* the Python package itself (defined by the directory py/desisim), not outside in some non-Python directory.  In other words, in order to continue to using `resource_filename()` these data files should be moved to py/desisim/data.

If on the other hand, there is overwhelming resistance to moving a few small data files to a standard location within the package that uses them, then some other function besides `resource_filename()` should be used to locate these files.

**Comment by moustakas** [comment]
Fixed in #102.
