### ISSUE TITLE
Where are the template .fits files?

### ISSUE THREAD

**Issue by ngbusca** [desihub/desisim#134]
I've pulled desisim and checked out desimodel from svn but the template .fits files required by quickbrick don't seem to be shipped on either... where can I get them from?

**Comment by moustakas** [comment]
Installation instructions are still under development (please send comments to @weaverba137 and/or @desi-data!), but see  https://desi.lbl.gov/trac/wiki/Pipeline/Install#Data  Specifically you need to get the basis templates and to set the $DESI_BASIS_TEMPLATES environment variable.

**Comment by weaverba137** [comment]
The documentation here addresses this problem: https://desi.lbl.gov/trac/wiki/Pipeline/Install#SetNecessaryEnvironmentVariablesandData
If this is insufficient, please open a new issue with specific concerns.
