### ISSUE TITLE
properly incorporate the Lyman-alpha forest into the QSO templates

### ISSUE THREAD

**Issue by moustakas** [desihub/desisim#153]
Coordinate with the Lyman-alpha Working Group to properly integrate the Lyman-alpha forest along various lines of sight with the QSO templates.

**Comment by ngbusca** [comment]
Added the branch lya_sims with the module lya_spectra to read the input lyman_alpha transmission files and add the absorption in the forest. 

TODO:

* Spectra are normalized to the given magnitud before adding the forest. Need to renormalize after addition of the forest

* Need to determine the size of the pixels (currently they are 2A wide, certainly too coarse)

**Comment by moustakas** [comment]
This was done in #156 with a speed-up in #210.
