### ISSUE TITLE
Is quickbrick doing the right thing?

### ISSUE THREAD

**Issue by moustakas** [desihub/desisim#160]
Please correct me if I'm wrong

**Comment by moustakas** [comment]
[Wow, that's funny -- some combination of keyboard shortcuts allowed me to post the shortest issue to ever make sense I've ever written.]

Let's flesh this out a bit -- My question is whether ```quickbrick``` is correctly implementing ```specsim```'s lunar model.  I was trying to figure out how ```specsim``` knows when to include the moonlight since the default lunar parameters are non-zero, to wit:
```
from specsim.simulator import Simulator
from desimodel.io import load_desiparams
desiparams = load_desiparams()
qsim = Simulator('desi')
qsim.atmosphere.moon.separation_angle
 <Quantity 60.0 deg>
qsim.atmosphere.moon.moon_phase
 <Quantity 0.5>
```

When ```desisim.scripts.quickbrick``` is called the only difference between bright- and dark-time "objects" (e.g., BGS vs ELG) is whether or not these parameters get set.  But then I noticed that there's a ```qsim.atmosphere.moon.visible``` parameter which by default is set to ```False```. And ```quickbrick``` never sets this to ```True```.

So bringing this back home, is ```quickbrick``` doing the right/wrong thing?

**Comment by moustakas** [comment]
All's well, apologies for the spam.  ```qsim.atmosphere.moon.visible``` is an internal attribute that gets set to ```True``` if the moon zenith angle is less than 90 degrees.  When we call ```quickbrick``` for any of the bright-time objects the default zenith angle is 30 and ```visible``` becomes ```True```.

**Comment by dkirkby** [comment]
@moustakas Its not an *internal* attribute, its part of the [documented public API](http://specsim.readthedocs.io/en/stable/api/specsim.atmosphere.Moon.html#specsim.atmosphere.Moon.visible) :-)
```
>>> help(qsim.atmosphere.moon.visible)
Help on property:

    bool: Read-only visibility of the moon.
    
    The visibility criterion is :attr:`moon_zenith` < 90 degrees.
```

**Comment by moustakas** [comment]
Apologies, that was my python newbieness (mis)speaking.  I meant that it's an attribute that gets set internally inside the code in a way that can't be changed externally, i.e., 
```
from specsim.simulator import Simulator
qsim = Simulator('desi')
qsim.atmosphere.moon.visible
Out[3]: array(False, dtype=bool)
In [4]: qsim.atmosphere.moon.visible = True
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-95d40e782b81> in <module>()
----> 1 qsim.atmosphere.moon.visible = True

AttributeError: can't set attribute
```
Always learning, please don't flame too viciously...

**Comment by dkirkby** [comment]
I probably got a bit carried away with python [@property decorators](http://www.programiz.com/python-programming/property) in that code :-)  You're not the first one to be surprised by how read-only attributes work, so perhaps they shouldn't be overused.
