### ISSUE TITLE
coverage tests broken

### ISSUE THREAD

**Issue by sbailey** [desihub/desisim#163]
Somewhere along the way we broke the travis -> coveralls connection.  Or coveralls.io is having trouble.  Either way coveralls.io is claiming that we have 0 test coverage for desisim:

https://coveralls.io/github/desihub/desisim

To do: Investigate why, and fix it.

**Comment by weaverba137** [comment]
The coverage dropped to zero as a result of PR #159, which changed the coverage tests from running in 2.7 to 3.5.  I don't know why 3.5 doesn't work, but at least it's a start.

**Comment by weaverba137** [comment]
Further detective work.  It looks like the problem is in the coverage package (the thing that actually calculates the coverage), not the coveralls package (the thing that transmits the coverage data to coveralls.io).
```
Coverage.py warning: No data was collected.
```
See https://travis-ci.org/desihub/desisim/jobs/160587521#L2348

**Comment by weaverba137** [comment]
Ah, right.  The coverage package is pinned at 3.7.1, & I'm going to guess that's not 3.5 compatible.  That version was recommended by astropy some time ago, but I doubt that's still the case.
