### ISSUE TITLE
newexp-desi for bright flavor fails with bitmask error

### ISSUE THREAD

**Issue by tskisner** [desihub/desisim#171]
I was just running newexp-desi and it always fails for bright exposure type with an error like:

> multiprocessing.pool.RemoteTraceback:
> """
> Traceback (most recent call last):
> File "/global/common/edison/contrib/desi/conda/conda_3.5-20160913/lib/python3.5/multiprocessing/pool.py",
> line 119, in worker
>     result = (True, func(*args, **kwds))
> File "/global/common/edison/contrib/desi/conda/conda_3.5-20160913/lib/python3.5/multiprocessing/pool.py",
> line 44, in mapstar
>     return list(map(*args))
> File "/scratch2/scratchdirs/kisner/software/desi-dev/desisim/master-061345e/lib/python3.5/site-packages/desisim-0.14.0.dev684-py3.5.egg/desisim/targets.py", line 138, in _wrap_get_targets
>     return get_targets(nspec, flavor, tileid, seed=seed, specmin=specmin)
> File "/scratch2/scratchdirs/kisner/software/desi-dev/desisim/master-061345e/lib/python3.5/site-packages/desisim-0.14.0.dev684-py3.5.egg/desisim/targets.py", line 361, in get_targets
>     fibermap['MWS_TARGET'][ii] = mws_mask.MWS_PLX  #- ???
> File "/scratch2/scratchdirs/kisner/software/desi-dev/desiutil/master-86835f2/lib/python3.5/site-packages/desiutil-1.8.0.dev347-py3.5.egg/desiutil/bitmask.py", line 256, in __getattr__
>     raise AttributeError('Unknown mask bit name ' + name)
> AttributeError: Unknown mask bit name MWS_PLX

This is using master versions of all packages from a few days ago.  I'm updating all packages now to see if it goes away, but I have not used desisim much and wanted to see if this is just user error :-)  For reference, the command that died above was:

> newexp-desi --night 20161221 --nspec 5000 --flavor bright --expid 22
--tileid 28814 --seed 1728931223

**Comment by sbailey** [comment]
Milky Way Survey targeting bit MWS_PLX was replaced in desitarget master, which then broke desisim that was using that bitname by default for MWS.  Options:
* the fix is in pending desisim PR #169 (waiting on whether we need a new tag of specsim, or whether a simple workaround in desisim itself is possible)
* or you can use desitarget 0.6.0 for now
* or you could make the one line fix of `fibermap['MWS_TARGET'][ii] = 1` instead of `mws_mask.MWS_PLX` in targets.py line 361.

**Comment by tskisner** [comment]
Ok, since the fix is imminent and I'm just running with master versions of everything, I can make a local hack and move on to testing the processing.  We can re-run with tagged versions of everything eventually for a more long-lasting set of simulation products.

**Comment by tskisner** [comment]
Fixed by #169
