### ISSUE TITLE
make reading cosmics faster

### ISSUE THREAD

**Issue by sbailey** [desihub/desisim#174]
`desisim.io.read_cosmics()` is surprisingly slow, requiring 20-30 seconds per cosmics realization.  This is because it is recalculating the observed readnoise via `astropy.stats.sigma_clipped_stats` every time.  We could make this faster by:
- pre-caching the observed readnoise in the cosmics template headers
- using a faster method such as normalized median absolute deviation instead of sigma_clipped_stats.

This isn't a dominate factor of the pixel simulation run time, but it is irritating and could be worth a quick fix.

**Comment by moustakas** [comment]
We're no longer doing large pixel simulations, so this ticket is probably obsolete, but in any case in a login node on cori I'm getting a ~3.5 second read time, about a factor of 5-8 faster than the reported 20-30 seconds, so I'm going to close this.
```
from desisim.io import read_cosmics
%timeit read_cosmics('/global/cfs/cdirs/desi/spectro/templates/cosmics/v0.3/cosmics-bias-b.fits')
3.61 s ± 100 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
