### ISSUE TITLE
comparison of quickgen and quickbrick

### ISSUE THREAD

**Issue by rstaten** [desihub/desisim#180]
Following @rkehoe discussion with @sbailey, this issue itemizes observed differences between quickgen and quickbrick to facilitate generation of common  code as raised by @dkirkby (eg. #178).  The main difference comes from the fact that quickgen uses files generated by newexp-desi as input for specsim, while quickbrick goes directly from templates to specsim simulation.

Relevant similarities include:
- Using specsim as a simulator for all three channels
- Taking moon parameters for bright time (quickgen also includes gray time)
- Outputting calibrated frame files

Relevant differences include:
- Quickgen uses a fibermap file generated by newexp-desi while quickbrick generates an empty fibermap file
- Quickgen obtains parameters such as airmass, exposure time, etc. from simspec files while quickbrick takes these parameters as input arguments
- In addition to calibrated files, quickgen also outputs sky, calibration, and uncalibrated frame files

Options for development include 1) leaving as is, 2) they could be combined by either essentially having if/else statements for quickgen vs. quickbrick, or 3) or by having input files for one (eg. quickbrick) transformed in code to the other (eg. make a mock simspec file from templates plus user parameters).   The latter option would potentially maximize reused code and allow new possibilities such as quickbrick running on simspec files or quickgen outputting to bricks on configuration.

**Comment by moustakas** [comment]
I very much support consolidating the functionality of these two scripts (i.e., either option 2 or 3, with option 3 being the most flexible but also the most amount of work).  In particular, I'll note that neither ```quickbrick``` nor ```quickgen``` (via ```newexp-desi```) currently allows the user to vary many/most of the myriad optional inputs to the template-generating code (for example, suppressing the color-cuts applied or changing the input apparent magnitude priors), which means that when these options are added they'll need to be added to *both* scripts --- unless those scripts are consolidated as proposed, of course.

**Comment by rkehoe** [comment]
Good to know of the potential downstream issues.  @rstaten has already a draft of 2) and it seems to suggest 3).  I favor option 3), but it needs to be done in such a way as to preserve the ease-of-use for the WGs that motivated quickbrick to begin with.

**Comment by rstaten** [comment]
I am also in favor of option 3. As @rkehoe mentioned, I have already written a working version of option 2, but it is very redundant. Both scripts follow essentially the same steps, so an if/else version wasn't difficult to produce, but I am starting to look into how they can perform these steps in unison. This would of course also include a refactoring of the unit tests and recently added integration test.

**Comment by rstaten** [comment]
If option 3 is chosen as the most reasonable option, here is a schematic version of how the code would function. If input is not provided by the data meeting on Tuesday, I will go ahead and work on this refactor.

take keywords (must either have simspec/fibermap files or provide brick)
set specsim as simulator

must have some form of a fibermap file:
    if simspec:
        read fibermap file
    elif bricks:
        create blank fibermap

set up spectra for simulation (either use newexp-desi output or generate spectra from templates):
    if simspec:
        read simspec file
        if arc exposure:
            must explode wavelength array for specsim simulation
    elif bricks:
        set up truth table
        generate templates
        fill in truth flux
        set up metadata

set observation parameters (this will expand as realism effects are added):
    if simspec:
        get airmass from simspec
        get exposure time from simspec
    elif bricks:
        set airmass via keyword (user or default)
        set exposure time via keyword (user or default)
    set moon parameters if bright or gray time

set up cameras, wavelength, and flux arrays to be filled by specsim

simulate sources via specsim

get flux and inverse variance from specsim
    if flat exposure:
        produce fiberflat
    elif arc exposure:
        produce arc frame
    else (science exposure):
        if bricks:
            produce brick file
        elif simspec:
            produce quickgen output

**Comment by moustakas** [comment]
This was done in #184.
