### ISSUE TITLE
function to create a `simtype`

### ISSUE THREAD

**Issue by forero** [desihub/desisim#181]
Using mock data from `targets` and `truth` files we want to generate a simulated spectrum on the fly. This spectrum should be of a `simtype` object. We need a function in `desisim` that returns `simtype` taking as inputs the targetting bits in `targets` and the `trutype` in the `truth` file.

**Comment by sbailey** [comment]
Note that this issue also applies to including target contaminants in quickcat even if we aren't simulating spectra.  We need to combine:
* truth column TRUETYPE (=what a redshift fitter should say, e.g. 'GALAXY', 'STAR', or 'QSO')
* target columns DESI_TARGET, MWS_TARGET, BGS_TARGET bits

e.g. TRUETYPE='STAR' with DESI_TARGET QSO bit set is a contaminant QSO target.  Quickcat would pass that forward as a SPECTYPE='STAR', while newexp/specsim/pixsim would simulate that as a star that passes QSO cuts.

For spectral simulation, things get tricky if more than one DESI_TARGET bit is set, which is possible.  Options from easiest to hardest, least realistic to most realistic:
* just simulate a target that matches TRUETYPE and don't worry about the target selection cuts for the targeting bits
* simulate a target that matches TRUETYPE and passes the cuts for one of the target bits (we have some hooks in place for that, but I don't think they are fully exercised)
* simulate a target that matches TRUETYPE and passes the cuts for all of the target bits (could get quite slow if the phase phase coverage of the two classes is small)

**Comment by moustakas** [comment]
Another related tidbit: the template-generating code is vectorized (by class), so we'll want to be smart about how we call it.  In other words, it's faster to generate 100 spectra (of the same class) than it is to generate one spectrum 100 times.

**Comment by sbailey** [comment]
This function was added as `desisim.targets.get_simtype` as part of PR #191 (Model quickcat for ELGs).  Closing ticket.
