### ISSUE TITLE
expand quickcat.get_observed_redshifts interface

### ISSUE THREAD

**Issue by sbailey** [desihub/desisim#182]
We have several different approaches in the works for quickcat, both in terms of which parameters affect the redshift efficiency and how the results are tuned.  TODO:

Expand the interface for `desisim.quickcat.get_observed_redshifts` to incorporate all of the possible inputs we might use.  Different methods can contribute functions that match that interface, possibly ignoring some of the inputs.  The current version is only based upon the true object type and redshift.  A more complete version could be:
```python
def get_observed_redshifts(objtype, truez, flux_g, flux_r, flux_z, oiiflux,
    seeing, transparency,
    moon_phase, moon_angle, moon_zenith,
    rfocal, 
    ):
    '''
    returns zobs, zerr, zwarn for input parameters
    
    Args (some may be ignored by some methods):
        objtype: 'ELG', 'LRG', 'QSO', 'BGS', 'MWS', or 'STAR'
        truez: true input redshift
        flux_g/r/z: photometric flux from input target catalog
        oiiflux: true [OII] flux in erg/s/cm2/Angstrom
        seeing: FWHM seeing during spectroscopic observation
        transparency: atmospheric transparency during spectro obs; float [0-1]
        moon_phase: 0.0=full moon to 1.0=new moon
        moon_angle: angle between object and moon in degrees
        moon_zenith: angle between moon and zenith in degrees
        rfocal: radius of the object location on the focal plane in mm
    
    Returns (zobs, zerr, zwarn):
        zobs: observed redshift
        zerr: gaussian sigma of error estimate on zobs
        zwarn: bitmask of warnings; 0=good

    All inputs and outputs are numpy arrays or None
    '''
```
Am I missing any other parameters that might be used?

The basic goal here is to standardize the interface to coordinate the different methods instead of having each one refactor quickcat in equivalent but incompatible ways.

**Comment by sbailey** [comment]
This will also require an update to `quickcat.quickcat` to accept an observing conditions table to get the seeing, transparency, and moon parameters for the spectroscopic observations.

Note: this interface is oriented around each spectroscopic observation generating a redshift; it doesn't allow for multiple exposures of the same object under different conditions to contribute to a single combined redshift.  I'm not sure how to support that without making this quickcat interface much messier.

**Comment by rkehoe** [comment]
In addition to your list, there are three other 'observational' effects that occur in BOSS systematics studies: local stellar density, airmass and galactic extinction.  Is the expectation that stellar density and galactic extinction will be taken care of by surveysim?  It would seem that in that case, we want to include airmass for quickcat.

As to multiple observations, would that not be better handled after the MTL loop, when all observations have been accrued?  This would seem to correspond to the runtime where redshifts are fitted after each observation.

**Comment by forero** [comment]
#186 took care of this.
