### ISSUE TITLE
document simple quicksurvey loop

### ISSUE THREAD

**Issue by sbailey** [desihub/desisim#183]
Preparations for the December 2016 OSU meeting will involve changing a lot of pieces that interface with each other, with the select_mock_targets + quicksurvey loop testing that all the pieces fit together.

TODO: document a simple set of steps to run select_mock_targets + quicksurvey loop from scratch that can be used for testing whether anything is broken.
* A preliminary version is at https://github.com/forero/SandboxDESI/blob/master/challenges/end2end2017/instructions.md
* Move this into an area where others can edit (e.g. wiki or desisim/docs)
* make an example `inputs.yaml` and `epochs*.txt` files such that the entire chain can be run in <30 minutes, ideally <10 minutes, e.g. in a cronjob or in a debug batch job.
* write code to evaluate whether quicksurvey actually worked

**Comment by forero** [comment]
The first three bullets are addressed in the latest version
https://github.com/forero/SandboxDESI/blob/master/challenges/end2end2017/instructions.md

Are those clear/useful enough?

**Comment by forero** [comment]
All the details are in this repo
https://github.com/forero/quicksurvey_example

@sbailey comments?

**Comment by sbailey** [comment]
Setup notes: At NERSC I've installed copies of fiberassign and the latest desisim (and dependencies) so that they are configured by
```
source /project/projectdirs/desi/software/desi_environment.sh
```
Right now I think the user just needs to get the latest copy of desitarget, e.g.
```
module unload desitarget
cd $SCRATCH/desi/code
git clone https://github.com/desihub/desitarget
export PYTHONPATH=`pwd`/desitarget/py:$PYTHONPATH
export PATH=`pwd`/desitarget/bin:$PATH
```
If we make an update to desisim that is required for this before another tag is made, the instructions would be similar for swapping that out instead of the default copy.

In the `quicksurvey` instructions, the option should be `-T .` instead of `-T inputs/`.

I like having this example as a github repo to clone and try.
Please transfer this repo to desihub ownership so that others can contribute.  We'll also want to add examples for connecting it to surveysim when that connection is re-established.

Would be good to reference in the top level README that there are also README files in the inputs and outputs.

**Comment by forero** [comment]
@sbailey transfered the repo to desihub and added mentions to the README files in the inputs/output. But failed to have the  `source` and `module load` working, but it's probably due to conflicts with my configuration files. 

I didn't get the comment about `quicksurvey` instructions,  `-T input/` is the right option when executing the example.

**Comment by sbailey** [comment]
quicksurvey_example will continue to evolve, but what is there is good enough for the purposes of closing this issue.
