### ISSUE TITLE
Add Christophe's redshift efficiency model to quickcat

### ISSUE THREAD

**Issue by sbailey** [desihub/desisim#188]
Add @cballand's redshift efficiency model to quickcat.  We believe that the structure is now ready for that, including Kyle's observing conditions efficiency model to layer on top of Christophe's efficiency vs. redshift and fluxes model.  Iterate with @forero as needed on quickcat interface.

Note: to fully complete this we need
* #187 to integrate quicksurvey and surveysim to have actual observing conditions to try
* desihub/desitarget#106 to have fluxes and shapes to include in the model

But we should be far enough along that Christophe could add his code to quickcat even if we can't fully test it yet.  If quickcat doesn't yet have dummy values for those parameters, @forero please add those to make it easier to test the loop.

**Comment by cballand** [comment]
Thanks @forero @sbailey for providing me with this interface. I'm going to incorporate the efficiency model early next week. The past two days, I developed an error model as a function of z and oii flux/mag that I will also include, so that we'll have a full quickcat for elgs, lrgs and qsos.

**Comment by sbailey** [comment]
fixed via #191
