### ISSUE TITLE
newexp-desi use specsim for fiberloss calculation

### ISSUE THREAD

**Issue by sbailey** [desihub/desisim#206]
Update newexp-desi to use specsim for fiberloss calculation

**Comment by dkirkby** [comment]
Here is a checklist for integrating the new specsim fiberloss capabilities with desisim:
- [ ] Finish desihub/specsim#53 and tag new version of specsim.
- [ ] Specify focal (x,y) for each fiber in a simulated exposure.
- [ ] Specify the ELG + LRG + BGS distributions of (size, shape) to sample from.
- [ ] Specify how seeing of each exposure is generated or input.
- [ ] Implement script to generate and save fiberloss files (details in #217).
- [ ] Implement interpolation in saved fiberloss files.
- [ ] Update `quickgen` to use new specsim batch API for simulating multiple fibers at once.

I have probably forgotten something so feel free to edit this list.

**Comment by moustakas** [comment]
I believe that all of these outstanding issues have been implemented in a variety of PRs; please reopen if not.
