### ISSUE TITLE
Implement script to generate and save tabulated fiberloss arrays

### ISSUE THREAD

**Issue by dkirkby** [desihub/desisim#217]
The new specsim fiberloss calculations rely on the GalSim external package.  In order to decouple GalSim from this package, we will implement a two-step process:
1. Generate and save tabulated fiberloss arrays using GalSim.
2. Generate simulated bricks by reading and interpolating from saved fiberloss arrays.

This issue to implement a script that uses specsim to perform step 1.  This is probably not the final solution, but lets us get most of the benefit of more realistic simulations quickly without any requirement to have GalSim installed in order to run `newexp_desi` and `quickgen`.

**Comment by moustakas** [comment]
I believe this was completed in #261.
