### ISSUE TITLE
Adding DLAs to QSO templates

### ISSUE THREAD

**Issue by profxj** [desihub/desisim#218]
Have started a branch (add_dlas) to inject damped Lya systems into
QSO spectra.

Am mainly touching lya_spectra.py
Will include Voigt profile generation routines.  
Might (eventually) push those to desiutils

**Comment by profxj** [comment]
How low should we go?    NHI = 10^19 ?

**Comment by dkirkby** [comment]
Ideally we want to go below the level where the DLA is easily detectable, to be able to study systematics of un-identified or poorly fit DLAs.  Of course such a study requires that we know the DLA truth parameters, so we need a mechanism to capture those somehow.

**Comment by profxj** [comment]
Agreed.  Am going to go down to 19.5

I only plan to include Lya absorption for now (i.e. no Lyb, Lyg, etc. and no Lyman Limit).

Holler if you really want more.  And then holler at @sbailey to let me import pyigm and linetools.  :)

**Comment by ngbusca** [comment]
Will DLA be placed in high absorption regions or randomly?

**Comment by profxj** [comment]
For now, randomly according to their incidence with redshift.

**Comment by moustakas** [comment]
This was done in #220.
