### ISSUE TITLE
templates.QSO().make_templates is slow

### ISSUE THREAD

**Issue by sbailey** [desihub/desisim#219]
Spinning a conversation with @profxj into an issue:

`templates.QSO().make_templates(n=100)` is surprisingly slow, especially given that `desisim.lya_spectra.get_spectra()` is fast and calls `templates.QSO().make_templates()`.

Figure out why and fix it.

**Comment by moustakas** [comment]
One difference is that `lya_spectra` passes the redshift to `QSO.make_templates` as an input.

**Comment by moustakas** [comment]
Fixed in #225.
