### ISSUE TITLE
Change log is not being updated.

### ISSUE THREAD

**Issue by weaverba137** [desihub/desisim#223]
The change log (doc/changes.rst) is rather obviously out of date.  Please remember to update this file when you make changes.  Who is responsible for the tags that didn't get their changes included?

**Comment by weaverba137** [comment]
Hmm, I may have been confused by the fact that 0.18.2 is listed as released when in fact it is not.  All I'm asking is that people pay attention to documentation.

**Comment by sbailey** [comment]
Looks like a typo (probably from me) while editing the change log for tag 0.18.1.  I just fixed that in master.
