### ISSUE TITLE
qsos with wrong redshift

### ISSUE THREAD

**Issue by ngbusca** [desihub/desisim#227]
@andreufont noticed that quasars returned by desisim.templates.make_templates are not at the specified redshift. I looked into it and found that the problem comes from desisim.qso_template.desi_qso_template : this function returns a quasar of redshift between the specified redshift and the specified redshift + z_wind, where z_wind = 0.2 by default. 

A solution is to explicitly set z_wind = 0 when constructing the object qso in desisim.lya_spectra (currently in l.88), but it doesn't fully solve the problem if the user explicitly passes a qso object to lya_spectra.get_spectra

@sbailey @moustakas @profxj Do we really want templates that by default are not exactly at the specified redshift?

**Comment by moustakas** [comment]
I think this is definitely a "feature" that we don't want.  `z_wind` was originally included by @profxj so I defer to him on how this should be handled.

**Comment by moustakas** [comment]
Fixed in #228.
