### ISSUE TITLE
pragmatically avoiding negative values in QSO templates

### ISSUE THREAD

**Issue by sbailey** [desihub/desisim#232]
The current QSO template generation code excludes PCA combinations that have negative flux ([desi_qso_templ line 346](https://github.com/desihub/desisim/blob/master/py/desisim/qso_template/desi_qso_templ.py#L346)).  This requires generating many more templates than are needed in the hopes that enough will pass this cut.  The current padding factor `ipad` of 20x isn't always sufficient, causing the code to crash.

This issue documents some implementation ideas for how to be robust against negative flux while not wasting memory and compute time on much larger ipad values.

#### The current negative flux check is for restframe wavelengths 900 < lambda < 5000 Angstrom.  Change that to checking only within the observer frame wavelength visibility window. ####

Ideally the templates would be valid over the full wavelength range for every realization, but my experience with fitting PCA to spectra is that often they have a good positive fit within the observer frame visibility window while allowing non-physical negativity outside of that.  We have tuned the coefficient means and sigmas to the fits to data within each redshift bin, and those coefficients likely represent combinations that wouldn't pass our current non-negativity cuts.

#### Work (more) iteratively ####

Rather than tune `ipad` to be some larger number for the worst case and have to generate many more templates than are needed for the typical case, work iteratively, e.g.

1. Generate N_perz spectra
2. Keep the good ones
3. If we don't have enough good ones yet, repeat until we do or some upper iteration limit is reached

We do still want to have some upper iteration limit to avoid wasting a huge amount of time in case input parameters mean that it really can't generate enough good QSOs, but the loop above would allow us to finish faster and in less memory in the typical case, while increasing the ipad upper iteration limit.

Note: the current code partially does this, only calculating the lookback distance and filling in the final output arrays for templates that pass non-negativity cuts, but it still generates a full `N_perz*ipad` templates as a starting point.  That could become prohibitive if we need larger `ipad`.

#### Use Gaussian or actual distribution of coefficients rather than uniform ####

Currently the coefficients are drawn uniformly within +/- 2sigma of their mean for each coefficient within each redshift bin ([L332-L333](https://github.com/desihub/desisim/blob/master/py/desisim/qso_template/desi_qso_templ.py#L332-L333)), meaning that they are spending more time exploring corners of phase space rather than the more peaky actual distributions.  Pulling from the actual distributions or from Gaussians would likely generate more combinations that pass cuts.

This touches upon the issue of whether the default for templates should be to span phase space uniformly or represent DESI-like distributions.  At minimum it could be useful to have this as an option that would pick whether PCA coefficients are draw uniformly or not.

---

Each of these could be implemented independently while being beneficial, so don't let problems with one prevent us from implementing another.  The above ideas are ordered by my guess for what is most important to least important.

**Comment by weaverba137** [comment]
In my experience, it is also possible for PCA to generate templates that are *entirely* negative.  They are good templates, but just happen to have an overall negative coefficient.  Thus it may be possible to recover some of the bad ones just by multiplying them by -1.

**Comment by ngbusca** [comment]
Is the simplest approach of iterating until one gets a positive continuum dramatically more inefficient?

**Comment by moustakas** [comment]
There's a related issue that could / should be addressed at the same time.  Once #234 has been merged we'll have the situation where if a generated template doesn't pass the color-cuts the code will return a spectrum of zeros (with a warning).  

The other classes in `desisim.templates` handle this by iterating over other combinations of priors, but `desisim.templates.QSO.make_templates` doesn't include this logic.  We should fix this.

**Comment by moustakas** [comment]
All suggestions were incorporated in #234.
