### ISSUE TITLE
gmag bug in quickcat?

### ISSUE THREAD

**Issue by moustakas** [desihub/desisim#251]
@forero Is [this code block](https://github.com/desihub/desisim/blob/master/py/desisim/quickcat.py#L207-L218) in `quickcat` a bug?

`DECAM_FLUX` returns fluxes in nanomaggies but line 218 treats the g-band flux as a magnitude.

[If this is indeed a bug I can fix it on the branch I'm working on now, which is updating the `targets` and `truth` tables to the latest imaging data model.]

**Comment by forero** [comment]
I don't know if that's a bug. It looks like it is one. 
Consult first with @cballand . He wrote those lines.

**Comment by moustakas** [comment]
Apologies, I thought you wrote `quickcat`, @forero!

**Comment by forero** [comment]
Don't worry! `quickcat` has been a real collaborative effort!

**Comment by cballand** [comment]
I had a quick look and I'm  not sure it's a bug (but I should check this in more detail): as far as true_gmag and qso_gmag_threshold are in the same units (nanomaggies), the flux ratio should be expressed as it is on line 218 (i.e., it should only depend on the difference true_gmag - qso_gmag_threshold).

**Comment by cballand** [comment]
In fact you're right, this is a bug, true_gmag is a flux in nanomaggies and should be converted into a magnitude before being used in line 218.

**Comment by moustakas** [comment]
OK, great.  I've fixed this in my branch and will merge after Stephen's PR.

**Comment by cballand** [comment]
Ok, thanks @moustakas

**Comment by moustakas** [comment]
Fixed in #252.
