### ISSUE TITLE
quickgen can't simulate spectra above 500

### ISSUE THREAD

**Issue by sbailey** [desihub/desisim#26]
Now that quickgen has been announced to the collaboration, bugs in it become high priority.

The options for simulating spectra above 499 appear to be broken.  All of these should work:
```
quickgen --simspec {simspecfile...} --fibermap {fibermapfile} --nspec 500 --nstart 500 --spectrograph 1
quickgen --simspec {simspecfile...} --fibermap {fibermapfile} --nspec 500 --nstart 500
quickgen --simspec {simspecfile...} --fibermap {fibermapfile} --nspec 1000
quickgen --simspec {simspecfile...} --fibermap {fibermapfile} --nspec 5000
```
But they all fail with some version of:
```
Simulating spectrum 500,  object type=ELG
Traceback (most recent call last):
  File "/project/projectdirs/desi/software/edison/desisim/master/bin/quickgen", line 257, in <module>
    nobj[j,i,:waveMaxbin[channel]]=results.nobj[waveRange[channel],i]
IndexError: index 500 is out of bounds for axis 0 with size 500
```
As a result, quickgen can only simulate spectrograph 0 and not 1-9.  Please fix.

**Comment by gdhungana** [comment]
@sbailey I just made a PR. The change is verified for all suggested options. Can even give any arbitrary values for nspec or nstart. like, 

quickgen --simspec {simspecfile...} --fibermap {fibermapfile} --nspec 240 --nstart 950
