### ISSUE TITLE
fiber acceptance fraction for BGS targets should depend on redshift

### ISSUE THREAD

**Issue by moustakas** [desihub/desisim#289]
The "fast" fiber acceptance (or fiberloss) fraction for BGS targets coded up in `simexp.simulate_spectra` is currently a constant / fixed, but the redshift dependence is non-negligible (more than a factor of two) due to the cosmological dependence of the angular diameter distance.  We should fix this.

The relevant portion of the code is roughly
https://github.com/desihub/desisim/blob/master/py/desisim/simexp.py#L473-L505

Also note that the correct link to the notebook from whence some of these numbers were derived is 
https://github.com/desihub/desitarget/blob/master/doc/nb/bgs-morphology-properties.ipynb
(i.e., part of master not the long-gone branch).

**Comment by moustakas** [comment]
@julienguy with the Director's review over would you be willing to fix this bug so I can revisit the BGS redshift efficiency calculations?

The relevant bit of code is in cell [16] of [this notebook](https://github.com/desihub/surveysim/blob/twilight/doc/nb/BGS_ETC_Study.ipynb) by @dkirkby, although this uses `astropy.cosmology` and you mentioned (over email, off-list) that you wanted a standalone cosmology module in `desisim` (I'm ambivalent).

**Comment by dkirkby** [comment]
It looks like the minimal fix required here is to replace these lines in simexp.py:
```
        source_half_light_radius[bgss,0]=4.7  # disk comp in BGS, arcsec
        source_half_light_radius[bgss,1]=1.3  # bulge comp in BGS, arcsec
```
with:
```
        LCDM = astropy.cosmology.Planck15
        angscale = (
            LCDM.angular_diameter_distance(0.1) /
            LCDM.angular_diameter_distance(source_redshift[bgss]).to(1).value
        source_half_light_radius[bgss,0]=4.7  * angscale
        source_half_light_radius[bgss,1]=1.3  * angscale
```
I made up `source_redshift` here, but presumably that array is available somewhere.

If someone wants to rewrite `astropy.cosmology.angular_diameter_distance`, then please include a unit test that compares against the astropy values.

**Comment by akremin** [comment]
Completed with the Bgsfibaccept pull request merger in desisim
