### ISSUE TITLE
quickgen outputs too many fiberflat spectra

### ISSUE THREAD

**Issue by sbailey** [desihub/desisim#29]
When running quickgen on a flavor=flat simspec exposure, it outputs a fiberflat-{brz}0-{expid}.fits file with 5000 spectra in the  even if the --nspec option was for fewer spectra.  It does use the --nstart option to figure out which spectrograph to start with, but it always rights 5000 spectra there.

e.g. `quickgen --simspec {simfile} --fibermap {fiberfile} --nspec 1000 --nstart 2000` should write `fiberflat-{brz}1*.fits` and `fiberflat-{brz}2*.fits`, each with 500 spectra.  Currently it write only `fiberflat-{brz}1*.fits` with 5000 spectra.

The equivalent options do work correctly for flavor=science exposures; this problem is only for the fiber flat output.

**Comment by gdhungana** [comment]
@sbailey  Ah I see! I'll look into this later tonight. Also I figured there is a bug in clipping simulated  flux  ivar that goes to cframe, which I have fixed in local copy but not pushed yet. Will push both soon.

**Comment by sbailey** [comment]
@gdhungana has this been resolved and we just forgot to close the ticket, or is this still an active issue?

**Comment by gdhungana** [comment]
This was resolved in the last commit and that pull request already merged. This must have been forgotten. For future, if I am assigned, would I feel free to close a ticket not initiated by myself?

**Comment by sbailey** [comment]
Normally I should remember to close the ticket when merging the pull request, but if you see a ticket that you clearly fixed and we just forgot to close it, it is ok for you to close it yourself.

**Comment by dkirkby** [comment]
A useful trick is to let github automatically close the issue using a [suitably formatted commit message](https://help.github.com/articles/closing-issues-via-commit-messages/).  The same syntax also works in the body of a PR (but not the title), although that isn't obvious from the docs.
