### ISSUE TITLE
update/change data model for template metadata?

### ISSUE THREAD

**Issue by moustakas** [desihub/desisim#290]
Currently the metadata table returned by the various template-generating methods in `desisim.templates` includes a mixture of type-specific columns (documented below). For example, the column `TEFF` is only populated when generating stellar templates and empty otherwise.  

I'm considering simplifying the output metadata table to only include basic info common to all templates (e.g., redshift, fluxes, templateid, etc) and to pack the rest of the information into an additional, type-specific metadata table, e.g., `GALMETA`, `STARMETA`, `QSOMETA`, which would be written out (if present) into a dedicated HDU.   

In particular, we are going to need *something* like this in order to accommodate the non-negligible number of model parameters controlling the `simqso` templates (see #152).  There's also precedent for an additional metadata table when adding DLAs to the QSO spectra (see #220).

This change will likely break a bunch of downstream code so there's no rush, but I'm opening the issue up for discussion.

```python
from desisim.io import empty_metatable
tt = empty_metatable()
tt.info()
<Table length=1>
   name     dtype       unit    
---------- ------- -------------
   OBJTYPE   str10              
   SUBTYPE   str10              
TEMPLATEID   int32              
      SEED   int64              
  REDSHIFT float32              
       MAG float32           mag
    FLUX_G float32   nanomaggies
    FLUX_R float32   nanomaggies
    FLUX_Z float32   nanomaggies
   FLUX_W1 float32   nanomaggies
   FLUX_W2 float32   nanomaggies
   OIIFLUX float32 erg / (cm2 s)
 HBETAFLUX float32 erg / (cm2 s)
     EWOII float32      Angstrom
   EWHBETA float32      Angstrom
     D4000 float32              
     VDISP float32        km / s
OIIDOUBLET float32              
 OIIIHBETA float32           dex
  OIIHBETA float32           dex
  NIIHBETA float32           dex
  SIIHBETA float32           dex
    ZMETAL float32              
       AGE float32           Gyr
      TEFF float32             K
      LOGG float32        m / s2
       FEH float32              
```
PS. The lack of units for all the columns is incompatible with `astropy 2.x`, so we'll have to fix this when we upgrade (related to #269).

**Comment by sbailey** [comment]
Do you have a proposal for what to do when we generate targets from more than one template type and then want to write them out to a single file (e.g. a simspec file)?  Currently this is written into the "TRUTH" HDU.  We could write one HDU with the common parameters and then one additional HDU per template type, including TARGETID in all of them to be able to cross match what is what.  Seems inconvenient, but perhaps no worse than having N>>1 columns in a single table where many of them don't apply to any given target.

Same issue applies for writing DLA-specific information that only applies to a small subset of the targets.

**Comment by moustakas** [comment]
@sbailey In the spirit of breaking things in August, I think I'd like to move forward with this issue. Any opinions, warnings, suggestions, guidance?

**Comment by sbailey** [comment]
Go ahead and break stuff if you think you can wrap it up in ~2 weeks.  Earlier comment/question still applies about needing a data model plan for how to write differing metadata for different kinds of targets into a single output file.

**Comment by moustakas** [comment]
Done in #409.
