### ISSUE TITLE
Lya forest is added twice in lya_spectra

### ISSUE THREAD

**Issue by andreufont** [desihub/desisim#291]
desisim.lya_spectra is supposed to add lya forest fluctuations from a file, but it currently calls 
qso.make_templates() without specifying lyaforest=False, what means that it gets a quasar template that already has (random, 1D) fluctuations. 
Then it reads the lya file, and adds extra fluctuations. 
I think this is trivially fixed by calling instead
qso.make_templates(lyaforest=False)

**Comment by moustakas** [comment]
Yes, nice catch. Would you mind fixing this?

**Comment by andreufont** [comment]
sure, I'll give it a try :-)

**Comment by andreufont** [comment]
Fixed in PR #292
