### ISSUE TITLE
New format for Lya skewers 

### ISSUE THREAD

**Issue by andreufont** [desihub/desisim#295]
Currently Lya skewer files from 3D boxes have a format where each quasar skewer has its own HDU, repeating the wavelength grid every time. 

We'll write a new format where we'll have wavelength in one HDU, and then a table of size Nqso x Npix in the other HDU.

We will not read magnitude from the lya skewer file, since the boxes only provide angular position and redshift, no magnitude.

**Comment by moustakas** [comment]
Just to add to this.  It would be helpful -- but not imperative -- if the new data model was accompanied by a new directory/organizational structure as well (also the structure currently used by the spectroscopic pipeline).  

The desired directory structure was discussed at length [here](https://github.com/desihub/desitarget/issues/195) but, to summarize, files should be organized into nside=8 healpixels with the format `{group}/{nside}-{pixnum}/{prefix}-{nside}-{pixnum}.fits` where `group` = `pixnum` // 100, `pixnum` is the healpixel, `nside`=8, and `prefix` is the specific filename prefix.

For convenience, there's also code to implement this structure:
https://github.com/desihub/desitarget/blob/master/py/desitarget/mock/io.py#L52-L84

And @andreufont it's fine if there's no magnitude information -- absolute magnitudes will be drawn from the QSO LF and the apparent magnitudes will be computed from the distance modulus and the K-correction from each individual spectrum self-consistently (see #293 for work in progress).

**Comment by andreufont** [comment]
That's great, thanks.
I've modified the CoLoRe transmission files to follow this structure, as in 
/project/projectdirs/desi/mocks/lya_forest/v2.0.0/7/748/transmission-8-748.fits
They are still with the old format, i.e., with one HDU per quasar. I'll implement the new format after the meeting (or on the hack day).

**Comment by moustakas** [comment]
This was done in #297.

**Comment by moustakas** [comment]
@andreufont @julienguy I'm finding that the wavelength sampling of the CoLoRe Lya forest spectra--approximately 5 Angstroms--is not sufficient for generating realistic DESI spectra.  For comparison, Jean-Marc's skewers -- the ones we were using previously -- were sampled at 0.2 A/pixel.  Is it simple enough to update the CoLoRe mocks?

**Comment by andreufont** [comment]
@moustakas - We will have spectra with higher resolution in a timescale of a few weeks, but meanwhile I thought we could just interpolate to create spectra on the fly with whatever resolution you need. I believe Julien was able to generate spectra with these files, not sure why you can not now.

**Comment by moustakas** [comment]
OK, thanks.  The interpolation code hasn't changed but the wavelength sampling is so low that linear interpolation does not yield DESI-like Lya forest spectra (e.g., spectra generated by simqso or the fast skewer Lya-forest maker).  I'll leave this issue open until we have the higher-resolution mocks incorporated, just as a reminder.

**Comment by andreufont** [comment]
Oh, I see. So it is not that the simulator is crashing, it is just that "by eye" they look like there is not enough small scale power, the variance is too low. Correct?
This is a well known issue, and we plan to fix it in the next iteration of CoLoRe mocks.

**Comment by moustakas** [comment]
Right.  I only "reported" it because it took me a little while to track down and I thought it was a problem on my end!

**Comment by moustakas** [comment]
@andreufont What is the redshift distribution of the new Lya skewers?  I spot-checked a couple healpixels and it looks like they start at z=2.  Meanwhile, the Gaussian random field mocks we're using (as produced by @fjaviersanchez and @dkirkby) have a high-redshift cut-off of z=1.6 (since the previous Lya skewers extended to z=1.6).  

So we either need to push the skewers to lower redshift or the GRF mocks to higher redshift.

**Comment by andreufont** [comment]
@moustakas - We can start the mocks pretty much at any redshift, at least from CoLoRe mocks (we can have them go all the way to z=0 if needed). Right now they go to z=3.7 Ithink, but we could extend a bit to higher redshift by using a larger box, but we would lose a bit of resolution.  For the next version we'll start at z=1.6.

**Comment by andreufont** [comment]
@moustakas - We should probably close this ticket. If there are still issues with the Lya mocks, we could open a new ticket.

**Comment by moustakas** [comment]
Yes, please feel free to close whatever tickets you think have been addressed.
