### ISSUE TITLE
dc17b: discrete input high z qso

### ISSUE THREAD

**Issue by ngbusca** [desihub/desisim#308]
In dc17b, the input redshifts for high z quasar (above ~1.7) are discrete. Here's a plot of z_fit vs. z_input with a zoom at the transition redshift.

![pastedgraphic-1](https://user-images.githubusercontent.com/4727509/34878286-53f10040-f7b2-11e7-98d2-3c343904e26c.png)

**Comment by moustakas** [comment]
Moved to https://github.com/desihub/desitarget/issues/260; closing here.
