### ISSUE TITLE
PSF is sharper in fast 1D simulations than in 2D spectroperf. extractions

### ISSUE THREAD

**Issue by julienguy** [desihub/desisim#318]
The PSF in the fast 1D simulations are sharper than the ones obtained with the 2D spectroperf. extractions.
Example: sky line in blue camera. both 1D and 2D have a wavelength step of 0.8A.

![figure_1](https://user-images.githubusercontent.com/5192160/35409680-d186ee74-01c7-11e8-8290-b732a1c69bf1.png)

This has to be fixed for redshift efficiencies estimates and meaningful comparison with simulations starting from CCD images.

**Comment by sbailey** [comment]
Possibly related to sqrt(2) mentioned in desihub/desispec#68 .  Need to double check that.  I don't think specsim uses desispec.resolution.Resolution, but the author is the same and if it is an error it may have occurred in two places.

**Comment by julienguy** [comment]
I think this is another issue: resolution is applied twice in the CCD image simulations!
- resolution applied once in specsim https://github.com/desihub/specsim/blob/a9ef6a5d66f5a8a321d54b6938d6f6dee94b84d2/specsim/simulator.py#L527
- the convolved spectra ( ```sim.simulated['num_source_electrons_'+camera]``` ```sim.simulated['num_sky_electrons_'+camera]```) are then saved in simspec files (HDUs PHOT_B,  SKYPHOT_B, ...)
- they are then read in ```desisim.scripts.pixsim.main```
- and projected on the CCD in ```desisim.pixsim.simulate```, effectively applying a second time the instrument resolution!
