### ISSUE TITLE
pixsim multiprocessing out of memory error at NERSC for typical test case

### ISSUE THREAD

**Issue by lastephey** [desihub/desisim#319]
Running this (and similar) pixsim tests at NERSC consistently result in the error: Exceeded job memory limit

job request: salloc -A desi -N 1 -t 2:00:00 -C haswell --qos=interactive

time pixsim --simspec $SCRATCH/desitest/data/simspec-00003578.fits \
    --rawfile $SCRATCH/temp/desi-00003878.fits.fz --cameras r0 --ncpu 32

This test failed on 01/26/2018 using the updated master version of both desisim and specter.

Is this test related to the upgrades in desiconda/the recent issues in redrock? Can others reproduce this result?

**Comment by sbailey** [comment]
I confirm that I also run out of memory on that command.  I checked my desitest logs and confirmed that it *did* work on January 8, i.e. just prior to the scheduled maintenance.  I'll submit a NERSC consult ticket.  This probably also explains why I'm running out of memory on redrock commands that I'm almost certain worked in December.

**Comment by sbailey** [comment]
NERSC confirmed that they changed how slurm monitors memory and I provided a test case showing that it was doing it wrong for python multiprocessing.  Doug Jacobsen at NERSC reported last night

> Yes, I've confirmed the issue and found the bug in slurm. It's been reported to our vendor and we'll work out a path to getting a correction in shortly

and then two hours later

> I've put in a workaround for the issue on cori, and I think we are seeing the correct behavior for memory limits now. The MaxRSS reported is still all kinds of wrong, and that has also been reported ... I do have some hope that we can get that normalized as well

But our jobs are working again including this pixsim case.  Thanks to Doug for the quick after-hours fix once it was reported.
