### ISSUE TITLE
Unclear logarithmic units in metatable

### ISSUE THREAD

**Issue by weaverba137** [desihub/desisim#335]
The function `desisim.io.empty_metatable()` returns a `astropy.table.Table` that has several columns with units of `dex`.  The question is `dex` of what?  That is, what are these values the logarithm of?  If I knew exactly, it might be possible to construct a column that had alternate units that were FITS-compliant.  See astropy/astropy#7279 for why this is important.

**Comment by moustakas** [comment]
These quantities are all logarithmic emission-line flux-ratios, i.e., `log_{10} ( flux1 / flux2 )`, where `flux1` and `flux2` are in units of `erg/s/cm2` but obviously the ratio is dimensionless.  Where I grew up `dex` is precisely the unit to be used in this situation, although maybe the young kids are using something different nowadays.

**Comment by moustakas** [comment]
Maybe the unit just needs to be capitalized?
  http://docs.astropy.org/en/stable/api/astropy.units.Dex.html#astropy.units.Dex

**Comment by weaverba137** [comment]
Hmm, I'll try that.

For the record, I have no problem with 'dex' in and of itself, as long as it is clear what it is the logarithm of.  I'm just trying to find a workaround for the bug I linked to.

**Comment by weaverba137** [comment]
Aha, my quick test script was fine with 'Dex'.  I'll see if that works on the full desisim test.

**Comment by weaverba137** [comment]
And it works in the main package.

**Comment by moustakas** [comment]
Excellent!  I came across this problem some time ago and wish I had discovered this easy fix myself.
