### ISSUE TITLE
Add option to generate quick Lya quasar mock from skewer

### ISSUE THREAD

**Issue by andreufont** [desihub/desisim#338]
Following the discussion with @julienguy and @sbailey:
 - Right now we can generate Lya mocks using transmission skewers read from a file.
 - The current code goes through target selection, fiber assignment, specsim... and then we run the DESI pipeline to get the calibrated spectra. 
 - While this is great, we would also like to be able to generate a much simpler mock spectrum, where we just take the input skewer, multiply by a random quasar continuum, and add DESI-like noise one spectrum at a time. No pipeline or fiber assignment involved.

**Comment by moustakas** [comment]
This should do it (for mock targets in the CoLoRe mocks in a single healpixel).  (And obviously you'll want to replace `dust_dir` with your own local/NERSC environment variable.)

```
from desitarget.mock.mockmaker import LYAMaker
from desisim.scripts.quickspectra import sim_spectra
seed = 123
healpixel = 26030
nside = 64
dust_dir = '/Users/ioannis/research/data/sfd_dustmaps/maps'
LYA = LYAMaker(seed=seed)
data = LYA.read(healpixels=healpixel, nside=nside, dust_dir=dust_dir)
flux, wave, meta, targets, truth = LYA.make_spectra(data)
sim_spectra(wave, flux, program='qso', spectra_filename='junk.fits', 
            sourcetype='qso', seed=seed)
```

**Comment by julienguy** [comment]
Thanks John. I will write a utility script based on this.

**Comment by moustakas** [comment]
Great.  Also, here's a notebook that goes into a little more detail about using `desitarget.mock.mockmaker` --
https://github.com/desihub/desitarget/blob/master/doc/nb/connecting-spectra-to-mocks.ipynb

I've been meaning to advertise this to the various working groups...

**Comment by julienguy** [comment]
Work in progress in PR #343 .

**Comment by andreufont** [comment]
@julienguy we can close this ticket, right?

**Comment by julienguy** [comment]
yes indeed
