### ISSUE TITLE
QA: algorithmic access to desi_qa_zfind metrics

### ISSUE THREAD

**Issue by sbailey** [desihub/desisim#346]
The plots output by `desi_qa_zfind` include metrics like efficiency, catastrophic failure rate, dv bias, dv RMS, but I don't see a way to algorithmically obtain those numbers.

* Provide a function to calculate those numbers given a redshift catalog and a truth table, without making plots.
* When running `desi_qa_zfind`, cache those numbers in a json (or equivalent) file in the qa directory along with the plots (e.g. for reading by other code to compare two productions and highlight changes).

**Comment by profxj** [comment]
Regarding algorithmically,  it is rather straightforward to generate
the stats from a list of fibermap_files.  This generates a Table that
merges the measured redshifts and the truth.  

If you wish to input a catalog and truth table, we'll need to be strict
on formatting, etc.

**Comment by sbailey** [comment]
Example inputs in `/project/projectdirs/desi/datachallenge/reference_runs/18.3`:
* redshift catalog: spectro/redux/mini/zcatalog-mini.fits
* superset truth table: targets/truth.fits

Note: `zcatalog-mini.fits` is a concatenation of individual zbest files (is that what you meant rather than fibermap files?) which was then joined with the input `targets/targets.fits` file (not the truth file, but the target catalog file like real data will have).  This is a standard pipeline output file.

I was thinking that you would define the minimal subset of columns that you need to be able to do the calculations using the same names that are in those files, e.g. something like
* redshift catalog must have columns `TARGETID`, `Z`, `ZWARN`, `SPECTYPE` (any others?)
* truth catalog must have columns `TARGETID`, `TRUEZ`, `TRUESPECTYPE` (any others?)

Or optionally provide a pre-joined single table that has all of those columns.

e.g. I'd be happy if the end-user code looked something like:
```
zcat = fitsio.read('spectro/redux/mini/zcatalog-mini.fits')
truth = fitsio.read('targets/truth.fits')
zqa_stats = desispec.qa.calc_zqa_stats(zcat, truth)
print(zqa_stats['QSO']['dv_rms'])
print(zqa_stats['QSO']['dv_bias'])
print(zqa_stats['QSO']['zeff'])
#- etc.
```

**Comment by profxj** [comment]
ok, I nearly have this.  Only column missing is DESI_TARGET.
I can add that, but inform me how to determine which of the 
STAR and WD TEMPLATETYPE's are MWS objects.  It must
be only a subset.

**Comment by profxj** [comment]
or if you can add DESI_TARGET to the truth table, we're all set.

**Comment by moustakas** [comment]
We could certainly add `DESI_TARGET` to the output `truth.fits` file, although it was intentionally left off.  It's true that not all `STAR`s and `WD`s are MWS targets -- some will be contaminants and/or standards.  

Is it too inconvenient to grab just the `DESI_TARGET` column from the `targets.fits` file? It's row-matched with `truth.fits` and should be pretty quick with `fitsio`.

**Comment by sbailey** [comment]
The input zcatalog-mini.fits file has DESI_TARGET since it is pre-join of the redshift catalog and the input targets catalog.

To identify MWS targets:
```python
from desitarget.targetmask import desi_mask
ii = (zcat['DESI_TARGET'] & desi_mask.MWS_ANY) != 0
```

**Comment by profxj** [comment]
That works perfectly well for me.  
Making it so..

**Comment by profxj** [comment]
Enabled by PR #349
