### ISSUE TITLE
QA: function to get redshift/classification confusion matrix

### ISSUE THREAD

**Issue by sbailey** [desihub/desisim#348]
Add a QA function that takes a redshift catalog and a truth table (or optionally a pre-merged table of both) and calculates the TRUESPECTYPE vs. SPECTYPE confusion matrix.  Consider returning this as a nested dictionary of dictionaries like

* `results[truespectype][spectype]` = number of targets that really were `truespectype` but were classified as `spectype` regardless of whether the redshift was right or not

I think that would be clearer than returning a 2D array plus arrays of names for how to interpret each axis.  Or make the case for some other format.

For convenience, even if `results[truespectype][spectype] = 0` for some combination of `truespectype, spectype`, that entry should be included in the nested structure.

**Comment by profxj** [comment]
Here is a rather straightforward working example:
https://github.com/desihub/desisim/blob/confuse_me/doc/nb/Confusion_matrix_spectypes.ipynb

If you are good with this @sbailey , I'll work it in to the spec_qa.

**Comment by sbailey** [comment]
Looks good.  Please proceed with that.

**Comment by sbailey** [comment]
Fixed in PR #359.  Closing.
