### ISSUE TITLE
galaxy spectra pick up color bias after addition of SN Ia

### ISSUE THREAD

**Issue by sybenzvi** [desihub/desisim#365]
![bgs_sn_tilt_vs_ratio](https://user-images.githubusercontent.com/7385438/40455989-24fda9c4-5ea4-11e8-9e29-5940b305788b.png)
During the DESI hack day we found that adding a SN to a host spectrum with desisim appears to "tilt" the summed spectrum according to the transmittance of the DECam g, r, and z filters. The tilt effect worsens as a function of SN/host flux ratio, i.e., the larger the ratio, the more extreme the tilt.

What should happen is that the summed host+SN spectrum will be higher than the host spectrum alone. This appears to be done correctly in the rest frame, but something is distorting the normalization after the redshift and filtering is applied.

See the attached figure and notebook for examples.
[sn_ia_norm_bias.pdf](https://github.com/desihub/desisim/files/2033187/sn_ia_norm_bias.pdf)

**Comment by moustakas** [comment]
Thanks for reporting this issue, @sybenzvi.  

I dug into the code and I'm confident that it's doing the right thing.  Remember that the simulated spectrum -- whether it has a SN in it or not -- is normalized to the desired magnitude (specified either via the `MAG` input or the `RMAGRANGE` prior).  As you add a SN to the galaxy with an increasing r-band flux ratio the net effect is to *tilt* or pivot the output spectrum around the effective wavelength of the r-band (normalization) filter.  

I tested this hypothesis in the code by turning off the magnitude normalization (by hacking `desisim.templates`!) and I get the plot below.

Let me know if this addresses your concern(s) and if so please feel free to close this issue.  

![test-sne-templates](https://user-images.githubusercontent.com/1431820/40569017-333047d2-6033-11e8-95e4-5a65c714aa12.png)

**Comment by moustakas** [comment]
For the record, the preceding plot was made with the code below, after changing [this line](https://github.com/desihub/desisim/blob/0.27.0/py/desisim/templates.py#L742) of desisim.templates from 
```blurflux = restflux[this, :] * magnorm[this]``` 
to 
```blurflux = restflux[this, :]```

```python
from desisim.templates import BGS
import matplotlib.pyplot as plt

seed = 1
nmodel = 4
mag = 19

bgs_sn = BGS(add_SNeIa=True)

fig, allax = plt.subplots(2, 2, figsize=(14,8), sharex=True, sharey=False)
for fratio in [0, 0.35, 0.65, 1.0]:
    allflux_sn, wave, allmeta_sn = bgs_sn.make_templates(nmodel=nmodel, seed=seed, 
      rmagrange=(mag, mag), sne_rfluxratiorange=(fratio, fratio), novdisp=True)
    for (ax, flux_sn, meta) in zip(allax.flatten(), allflux_sn, allmeta_sn):
        epoch, snid = meta['SNE_EPOCH'], meta['SNE_TEMPLATEID']
        ax.plot(wave, flux_sn, label='Ratio={:.2f}, Epoch={:g}, ID={:d}'.format(
          fratio, epoch, snid))
        ax.set(title='$m$={:.2f},  $z=${:.2f}'.format(meta['MAG'], meta['REDSHIFT']))
    for ax in allax.flatten():
        ax.legend(fontsize=12)
fig.tight_layout()
fig.savefig('test-sne-templates.png')
```

**Comment by sybenzvi** [comment]
Thanks @moustakas. I buy the explanation, but I need to convince myself that this will provide a reasonable test of comparing hosts and hosts+supernovae. It shouldn't affect classifiers, but it could be a problem for Or's model-independent check for transients. He suggested looking at magnitude differences between the target measurement from the imaging surveys and the DESI observation as a signal of time-dependent changes in the galaxy flux. To test that, I think we need to scale the bolometric fluxes of the host + SN, and not scale to just the r-band.

**Comment by moustakas** [comment]
Right, I agree that the overall/total r-band magnitude can and will brighten with the transient, but that's the responsibility of the simulation to determine the amount of brightnening (see, e.g., @orgraur's [DESI_plant_fake_SNe.ipynb](https://github.com/desihub/desisim/blob/sne-sims/doc/nb/DESI_plant_fake_SNe.ipynb) notebook, which really should get merged to master), not the template-generating code.

**Comment by sybenzvi** [comment]
OK, I'm going to close the issue since we agree it's not a bug. This may reappear as a feature request instead after some further conversation with Or. Thanks again.
