### ISSUE TITLE
for some random cases gdz has only 1 element

### ISSUE THREAD

**Issue by alxogm** [desihub/desisim#375]
I can fix this at this level. But I'd like to know if it would be better to catch the error before calling the function, may be is a generic error if zem \sim zlya...

https://github.com/desihub/desisim/blob/a14b404a4d9cef1fdfe9632705107787d6d8044f/py/desisim/dla.py#L48

**Comment by alxogm** [comment]
This makes  quickquasars with --dla random crashes for some spectra in some pixels and for some random seeds... but stops the full simulation.

**Comment by julienguy** [comment]
Please fix this at this level.
