### ISSUE TITLE
in newexp_mock:   KeyError: "Extension 'FIBER_ASSIGNMENTS' not found."

### ISSUE THREAD

**Issue by moustakas** [desihub/desisim#378]
In https://github.com/desihub/fiberassign/pull/116 but perhaps elsewhere, the extension names of the files written out by fiber assignment changed, e.g., `FIBER_ASSIGNMENTS` is now `FIBERASSIGN`.

I fixed `fiberassign/bin/qa-fiberassign` in https://github.com/desihub/fiberassign/pull/126 but now it looks like `newexp_mock` (and perhaps other downstream code in other packages) is affected.  

I'm working on a PR but I'm surprised that our integration test and/or [minitest](https://github.com/desihub/desitest/blob/master/mini/minitest.ipynb) didn't catch this change in the data model sooner.

**Comment by sbailey** [comment]
Thanks for catching this.  minitest would catch this but it isn't run daily.  The daily "integration test" is just for the spectro pipeline and doesn't go upstream to targets and fiberassign.

Note: minitest notebook full integration is currently hung on desihub/desitarget#323 where select_mock_targets got much slower with a newer desiconda.

**Comment by moustakas** [comment]
Done in #380.
