### ISSUE TITLE
newexp_mock assumes nside=64 healpixels

### ISSUE THREAD

**Issue by moustakas** [desihub/desisim#379]
`newexp_mock` (called by `bin/wrap-newexp`) calls `simexp.get_mock_spectra` which calls `simexp.targets2truth` which assumes that the mock spectra are organized into `nside=64` healpixels.

Is this the standard because of, e.g., limitations of the downstream pipeline / redshift fitting?  (I used `nside=32` when generating mock spectra.)

It's an easy fix but if `nside=64` is preferred please let me know.

**Comment by sbailey** [comment]
The downstream pipeline uses nside=64 as a balance between number of files and number of spectra per file.  The basic unit of redshift fitting parallelism is the healpixel so going larger than that can cause some very large slow pixels.

However, the downstream pipeline shouldn't care what nside the mocks used though I tend to default to using nside=64 everywhere out of habit/consistency.  Feel free to make that an option for newexp_mock; even if I continue to use nside=64, that shouldn't be a hardcoded requirement.

**Comment by moustakas** [comment]
OK, thanks for the clarification.

**Comment by moustakas** [comment]
Done in #412.
