### ISSUE TITLE
Adding BALs does not work when generating full DESI with quickquasars

### ISSUE THREAD

**Issue by andreufont** [desihub/desisim#398]
Hi @LuzGarciaP @alxogm @paulmartini @forero @julienguy 

Something quite strange is going on. For instance, when I run a single quickquasars script with the option --balprob 0.12, everything works fine, and indeed I get some spectra with BAL features.

However, when I run the full slurm script to generate a full DESI simulation (see attached script, based on the original one by Julien Guy), I get the following error message:
AttributeError: 'NoneType' object has no attribute 'insert_bals'

It looks like somehow, the BAL object that should be created in line 503 is not created, and a None object is passed to simulate_one_pixel.

Can you reproduce this error? Any idea for how to fix it?

--- slurm script ---

#!/bin/bash -l

#SBATCH -C haswell   
#SBATCH --partition=debug
#SBATCH --account=desi
#SBATCH --nodes=40
#SBATCH --time=00:30:00
#SBATCH --job-name=lyasim
#SBATCH --output=lyasim.log

seed=123
downsampling=0.40
idir=/project/projectdirs/desi/mocks/lya_forest/london/v2.0/
outdir=/project/projectdirs/desi/mocks/lya_forest/london/v2.0/quick-1.7/
nodes=40 # CHECK MATCHING #SBATCH --nodes ABOVE !!!!
nthreads=4 # TO BE TUNED ; CAN HIT NODE MEMORY LIMIT ; 4 is max on edison for nside=16 and ~50 QSOs/deg2

if [ ! -d $outdir ] ; then
    mkdir -p $outdir
fi    
if [ ! -d $outdir/logs ] ; then
    mkdir -p $outdir/logs
fi
if [ ! -d $outdir/spectra-16 ] ; then
    mkdir -p $outdir/spectra-16
fi

echo "get list of skewers to run ..."

files=`\ls -1 $idir/*/*/transmission*.fits`
nfiles=`echo $files | wc -w`
nfilespernode=$((nfiles/nodes+1))

echo "n files =" $nfiles
echo "n files per node =" $nfilespernode

first=1
last=$nfilespernode
for node in `seq $nodes` ; do
    echo "starting node $node"

    # list of files to run
    if (( $node == $nodes )) ; then
	last=""
    fi
    echo ${first}-${last}
    tfiles=`echo $files | cut -d " " -f ${first}-${last}`
    first=$(( first + nfilespernode ))
    last=$(( last + nfilespernode ))
    command="srun -N 1 -n 1 -c $nthreads  quickquasars --exptime 4000. -i $tfiles --zmin 1.8 --nproc $nthreads --outdir $outdir/spectra-16 --downsampling $downsampling --zbest --mags --desi-footprint --seed $seed --balprob 0.12"
    echo $command
    echo "log in $outdir/logs/node-$node.log"
    
    $command >& $outdir/logs/node-$node.log &
    

done

wait
echo "END"

**Comment by alxogm** [comment]
@andreufont  I guess more information of this failure is in the log files of your runs in nersc? If so can you point me to which files look at so that I can try to reproduce the error? Thanks.

**Comment by andreufont** [comment]
Yes, the script is in 
/project/projectdirs/desi/mocks/lya_forest/london/v2.0/quick-1.7/run
And the log files are in 
/project/projectdirs/desi/mocks/lya_forest/london/v2.0/quick-1.7/logs

**Comment by julienguy** [comment]
it's a simple bug I am fixing now

On Wed, Aug 1, 2018 at 8:38 AM, Andreu Font-Ribera <notifications@github.com

**Comment by julienguy** [comment]
I committed the fix in desisim master (without going to a new branch).
Andreu, can you please test this?

**Comment by andreufont** [comment]
Hi @julienguy - I checked the new version, it works great. I already added a version with BALs in 
/project/projectdirs/desi/mocks/lya_forest/london/v2.0/quick-1.8
