### ISSUE TITLE
newexp-desi outputs photons in 10^-17 units

### ISSUE THREAD

**Issue by gdhungana** [desihub/desisim#40]
@sbailey newexp-desi is outputing photons in 10^-17 units. Earlier the true flux were also in the units of "10^-17 erg/s/cm2/A' that would go as input also in quicksim. Now both flux and photons are ~ 10^-17 ergs/s/cm2/A. Looks like a unit bug in desimodel.io.throughput ?

In [2]: import astropy.io.fits as fits

In [3]: sim=fits.open('simspec-00000002.fits')

In [4]: sim.info()
Filename: simspec-00000002.fits
No.    Name         Type      Cards   Dimensions   Format
0    PRIMARY     PrimaryHDU      13   ()              
1    WAVE        ImageHDU         9   (31901,)     float64   
2    FLUX        ImageHDU         9   (31901, 10)   float32   
3    SKYFLUX     ImageHDU         8   (31901,)     float32   
4    WAVE_B      ImageHDU         9   (12326,)     float64   
5    PHOT_B      ImageHDU         8   (12326, 10)   float32   
6    SKYPHOT_B   ImageHDU         7   (12326,)     float32   
7    WAVE_R      ImageHDU         9   (11205,)     float64   
8    PHOT_R      ImageHDU         8   (11205, 10)   float32   
9    SKYPHOT_R   ImageHDU         7   (11205,)     float32   
10   WAVE_Z      ImageHDU         9   (12765,)     float64   
11   PHOT_Z      ImageHDU         8   (12765, 10)   float32   
12   SKYPHOT_Z   ImageHDU         7   (12765,)     float32   
13   METADATA    BinTableHDU     20   10R x 5C     [10A, J, E, E, E]   

In [5]: sim[2].data[0]
Out[5]: 
array([  3.15100754e-20,   3.10153406e-20,   3.03663754e-20, ...,
         2.22941950e-17,   2.20956452e-17,   4.23840662e-17], dtype=float32)

In [6]: sim[5].data[0]
Out[6]: 
array([  1.26388593e-20,   1.24530337e-20,   1.22048011e-20, ...,
         1.61152245e-19,   1.33352876e-19,   1.40780001e-19], dtype=float32)

**Comment by moustakas** [comment]
I may have broken this (or fixed this, depending on your perspective).  Did we decide to normalize the (simulated) *data* by 10^-17?

**Comment by gdhungana** [comment]
I had thought so. Actually, we have been using flux in 10-17 ergs/s/cm2/A units for quicksim also. For pixsim, we were using photons counts. In the same example above, the sky photons however are not normalized by 10^-17. 
In [9]: sim[6].data
Out[9]: 
array([ 4.319839  ,  5.3053894 ,  4.92212629, ...,  1.07693553,
        1.04939353,  0.99386698], dtype=float32)

**Comment by moustakas** [comment]
Thanks for the clarification.  For the object spectra at least I think a simple multiplicative factor included in desisim.targets.get_targets() should do the trick.  (Unfortunately I can't fix this right now so please feel free...)

**Comment by gdhungana** [comment]
I think what you are saying will do. Noting that the dc2 templates had
absolute units, wouldn't it make more sense to get the targets' simulated
outputs in true units and make this adjustment in
desisim.obs.new_exposure() where you apply the throughput based on the
desired units/normalisation. The skyphot also seem to have been adjusted
there.

**Comment by dkirkby** [comment]
On the specsim side, the relevant API is [here](http://specsim.readthedocs.org/en/latest/api/specsim.spectrum.SpectralFluxDensity.html#specsim.spectrum.SpectralFluxDensity) and allows the flux units to be specified explicitly (using `astropy.units`) or defaults to `<Quantity 1e-17 erg / (Angstrom cm2 s)>` when no units are provided.  I would recommend that desisim code specify its units explicitly when calling specsim (or the soon-to-be-obsolete quicksim which has the same API), rather than relying on the default behavior.
