### ISSUE TITLE
Different HEALPix pixels should use different seeds in quickquasars

### ISSUE THREAD

**Issue by andreufont** [desihub/desisim#405]
@londumas noticed that we are currently reusing the same seed for some of the quasars, depending on the number of nodes we use. 

This should be trivial to fix in quickquasars.py by doing 

seed = seed + HEALPIX_pixel

**Comment by londumas** [comment]
@andreufont, this shouldn't be fixed at the `quickquasars.py` level but at the `quickquasar_slurm_script.sh` level.

**Comment by andreufont** [comment]
On 13 August 2018 at 16:56, Hélion du Mas des Bourboux <
notifications@github.com> wrote:

> @andreufont <https://github.com/andreufont>, this shouldn't be fixed at
> the quickquasars.py level but at the quickquasar_slurm_script.sh level.
>
I don't think so, I think it would be better to fix at quickquars.py, since
it is easier to access the healpix pixel in there, isn't it?

Andreu

**Comment by londumas** [comment]
ok, it is way easier at the `quickquasars.py` level, let's do that, but it is not very beautiful.
It is counter intuitive. In a script if I say: `--seed 42`, then I expect a line like `np.random.seed(42)`. I don't expect a line like `np.random.seed(42+some_number)`.

**Comment by londumas** [comment]
@andreufont, let me do the PR.

**Comment by andreufont** [comment]
Sounds good. I don't think it is ugly, --seed 42 does control the seed for the whole run, and if you change it you will change all the seeds at once.

Please go ahead with the PR

**Comment by londumas** [comment]
@andreufont, it is already implemented actually:
`    seeds = np.random.randint(2**32, size=len(args.infile))`. Do you agree?

**Comment by andreufont** [comment]
@londumas - No, this is what I meant that each pixel *within a node* will have a different seed. But the first pixel of each node will have the same random seed.

I would change that line for 
seeds = seed + healpix_pixel

**Comment by londumas** [comment]
@andreufont. ok, I see.

**Comment by londumas** [comment]
With this script and the PR https://github.com/desihub/desisim/pull/406, it will work very well. Each file will have a different seed:
```
#!/bin/bash -l

#SBATCH -C haswell   
#SBATCH --partition=debug
#SBATCH --account=desi
#SBATCH --nodes=40
#SBATCH --time=00:30:00
#SBATCH --job-name=lyasim
#SBATCH --output=lyasim.log

seed=123
downsampling=0.40
idir=/project/projectdirs/desi/mocks/lya_forest/london/v2.0/
outdir=/project/projectdirs/desi/mocks/lya_forest/london/v2.0/quick-1.4/
nodes=40 # CHECK MATCHING #SBATCH --nodes ABOVE !!!!
nthreads=4 # TO BE TUNED ; CAN HIT NODE MEMORY LIMIT ; 4 is max on edison for nside=16 and ~50 QSOs/deg2

if [ ! -d $outdir ] ; then
    mkdir -p $outdir
fi    
if [ ! -d $outdir/logs ] ; then
    mkdir -p $outdir/logs
fi
if [ ! -d $outdir/spectra-16 ] ; then
    mkdir -p $outdir/spectra-16
fi

echo "get list of skewers to run ..."

files=`\ls -1 $idir/*/*/transmission*.fits`
nfiles=`echo $files | wc -w`
nfilespernode=$((nfiles/nodes+1))

echo "n files =" $nfiles
echo "n files per node =" $nfilespernode

# Random seeds
get_seeded_random()
{
    thisseed="$1";
    openssl enc -aes-256-ctr -pass pass:"$thisseed" -nosalt \
    </dev/zero 2>/dev/null;
}
randoms=($(shuf --random-source=<(get_seeded_random $seed) -i 0-999999999 -n $nfiles))


first=1
last=$nfilespernode
for node in `seq $nodes` ; do
    echo "starting node $node"

    # list of files to run
    if (( $node == $nodes )) ; then
        seeds=(${randoms[@]:$first-1})
        last=""
    else
        seeds=(${randoms[@]:$first-1:$nfilespernode})
    fi

    echo ${first}-${last}
    tfiles=`echo $files | cut -d " " -f ${first}-${last}`   
    first=$(( first + nfilespernode ))
    last=$(( last + nfilespernode ))
    command="srun -N 1 -n 1 -c $nthreads  quickquasars --exptime 4000. -i $tfiles --zmin 1.8 --nproc $nthreads --outdir $outdir/spectra-16 --downsampling $downsampling --zbest --mags --desi-footprint --seed ${seeds[*]} --metals all" 
    echo $command
    #echo "log in $outdir/logs/node-$node.log"

    #$command >& $outdir/logs/node-$node.log &
    
done

wait
echo "END"
```

**Comment by julienguy** [comment]
you may commit your edits to the slurm script in desisim/etc/quickquasar_slurm_script.sh

**Comment by londumas** [comment]
Thank you @julienguy, I just committed the update of the script to the PR.

**Comment by sbailey** [comment]
For consideration, pseudocode for handling this within python instead of generating the seeds in the wrapper slurm script:
```python
def blat(thispixel, nside, seed):
    seeds = np.random.randint(2**32, size=healpy.nside2npix(nside))
    r = np.random.randomstate(seeds[thispixel])
    #= use r for generating other random numbers
```

Comparison to other suggestions:
* `seed = seed + HEALPIX_pixel` : seed=0 pixel=1 ends up with same randoms as seed=1 pixel=0
* `seeds = np.random.randint(2**32, size=len(args.infile))` depends upon how many infiles are passes and which ones they are.  Generating one seed per healpix and then picking which one to to use for *this* healpix gets around that.
* generating it in the script: ok, but would be nice if the python code was self-contained for randomness and didn't require specialized slurm wrappers to use it properly.

**Comment by andreufont** [comment]
I agree with Stephen, I find it simpler to have a single global seed, and
have a short function that uses that global seed and returns a seed for
each HEALPix pixel. I find the slurm magic very difficult to read, and I'd
prefer to have short scripts.

Andreu

**Comment by londumas** [comment]
closed via https://github.com/desihub/desisim/pull/406
