### ISSUE TITLE
Does qso_template need to be a separate package?

### ISSUE THREAD

**Issue by weaverba137** [desihub/desisim#41]
In the py/ directory, there are two packages, desisim, and qso_template.  The latter hasn't been touched in some time.  Is it still necessary to keep it separate, or can it be folded into desisim?

**Comment by moustakas** [comment]
@profxj and I need to touch base to coordinate integrating the QSO stuff into desisim.  We will be sure to clean up this directory/branch when we've completed our work.

**Comment by profxj** [comment]
It can definitely be folded in.

Cheers,

X

> On Nov 9, 2015, at 11:24 AM, Benjamin Alan Weaver <notifications@github.com> wrote:
> 
> In the py/ directory, there are two packages, desisim, and qso_template. The latter hasn't been touched in some time. Is it still necessary to keep it separate, or can it be folded into desisim?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/desihub/desisim/issues/41>.
> 
> !DSPAM:826,5640f30121271208153734!

----------------------------------------------
J. Xavier Prochaska
UCO/Lick Observatory
1156 High St.
UC Santa Cruz
Santa Cruz, CA 95064

http://www.ucolick.org/~xavier/
http://imps.ucolick.org/
http://www.qpqsurvey.org/
http://k1dm3.ucolick.org/
http://www.ucolick.org/~xavier/IDL/index.html
https://github.com/xastropy/xastropy
https://github.com/linetools/linetools

831-459-2135 (Direct)
831-459-2991 (UCO/Lick Main)
831-459-5244 (Fax)

**Comment by sbailey** [comment]
Fixed in PR #67
