### ISSUE TITLE
fix quickquasars; write out truth metadata

### ISSUE THREAD

**Issue by moustakas** [desihub/desisim#411]
#409 likely broke `quickquasars`.

One immediate issue is that the "normalization filter" argument needs to be explicitly passed as either `normfilter_south` or `normfilter_north` for quasars observed in the DECaLS vs BASS/MzLS filters.

When making these changes we should also write out the "truth" metadata tables as an additional output file as we do in `desitarget.build` (via `desitarget/bin/select_mock_targets`).

**Comment by andreufont** [comment]
@moustakas - it would be great if quickquasars in the master branch was always working, since this is an important code used very often in the Lyman alpha working group. 

I guess this means we should setup a test in Travis for it? 

@alxogm - Tell your students that quickquasars is broken, but it looks like the fix should be easy.

**Comment by alxogm** [comment]
Hi @moustakas, I made the test of not passing any argument, as I saw normfilter_north/south has defaults. But  the default  normfilter_north='BASS-r' sends the error 

 No such group 'BASS'. Choose one of ['sdss2010', 'decam2014', 'wise2010', 'hsc2017', 'lsst2016', 'bessell'].

(in templates.py:SIMQSO() but I think is the same for QSO() and others)

What should I choose?

**Comment by moustakas** [comment]
You need the master branch of speclite until @dkirkby creates a new tag.  

Please see the thread here:
https://github.com/desihub/redrock/issues/150

**Comment by moustakas** [comment]
And just for the record: I'm fixing what's broken with `quickquasars` (independent of the issue with `speclite`) in the `fix-quickquasars` branch and should have that ready for review soon.

**Comment by alxogm** [comment]
OK. Now it works. Thanks! @moustakas 

The quickquasars flag '--norm-filter' was set as default for "decam2014-g", that corresponds to normfilter_south.   Shall I add both north and south to the quickquasar options?  or just leave it as it is, and pass normfilter_south=args.norm-filter to SIMQSO( ) and leave north as the default?

**Comment by moustakas** [comment]
I've made these changes in my branch already.  I'm working on passing forward and writing out the metadata table, so you can add to that.

**Comment by alxogm** [comment]
@moustakas ok! thanks.  So I'll wait for your changes.

**Comment by moustakas** [comment]
Done in #413.
