### ISSUE TITLE
add AGN-like emission lines to the LRG templates

### ISSUE THREAD

**Issue by moustakas** [desihub/desisim#418]
A long-standing ToDo is to add ~weak emission lines with AGN-like line-ratios to the LRG templates.  Do this.

@londumas if you have any suggestions or insights from your fitting of the eBOSS/LRG sample I would be grateful for your input.

**Comment by moustakas** [comment]
Yes, that'd be helpful.

**Comment by londumas** [comment]
With a subsample of 10,000 eBOSS LRG, there doesn't seem to be an issue in any of the BGS, ELG, LRG templates. Please keep in mind that an LRG can be best fit by a BGS or an ELG or a LRG archetype.
Do you need more LRG? A given subsample?

![lrg](https://user-images.githubusercontent.com/3166436/45579667-e7254100-b846-11e8-95d4-fe6573b2461f.png)

**Comment by moustakas** [comment]
No plan to implement this enhancement now that we have actual data to work with.
