### ISSUE TITLE
Bug with desi_environment

### ISSUE THREAD

**Issue by TEtourneau** [desihub/desisim#421]
Hello,

I used to load the desi_environment to run quickquasars by doing this : 

source /project/projectdirs/desi/software/desi_environment.sh master

But it seems that since the last night maintenance, gcc is not available anymore and so the desi_env cannot be load : 

gcc(3):ERROR:105: Unable to locate a modulefile for 'gcc/7.2.0'

I am the only one experiencing this ? Any solution ?

Thank you in advance,
Thomas

**Comment by sbailey** [comment]
NERSC removed the gcc/7.2.0 module during the Cori maintenance yesterday, which appears to be an error.  I have asked them to restore it.

**Comment by sbailey** [comment]
NERSC has restored the gcc/7.2.0 module and the desi environment works again on cori.  Please re-open if you continue to have problems.
