### ISSUE TITLE
Bug in quickquasars

### ISSUE THREAD

**Issue by TEtourneau** [desihub/desisim#432]
Hi,

I just tried to run quickquasars, as usual, but a bug occured. 
I ran quickquasars on cori nodes, using the last version of master branch. (I can link the sbatch script I use to run it if it's usefull).
Here is what I get: 

'''
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desisim/master/bin/q
uickquasars", line 9, in <module>
    sys.exit(main())
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desisim/master/py/de
sisim/scripts/quickquasars.py", line 678, in main
    pool.map(_func, func_args)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/multi
processing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/multi
processing/pool.py", line 644, in get
    raise self._value
ValueError: no field of name Z_noRSD
srun: error: nid00645: task 0: Exited with exit code 1
srun: Terminating job step 15445182.18
'''

**Comment by andreufont** [comment]
Hi @TEtourneau - Sorry for that. This is due to some recent changes by @alxogm and myself, where we were trying to update the truth files for the simulated quasar spectra. 

The idea was to store both the redshift of the quasar including RSD, and the redshift of the quasar without the RSD, but we should first check if these entries exist before trying to read them.

**Comment by andreufont** [comment]
While we wait for this to be fixed, you can comment out line 534 in quickquasars.py

**Comment by TEtourneau** [comment]
Hi Andreu,

Ok, no worries. I'll comment out this line.
Thanks

**Comment by alxogm** [comment]
@TEtourneau sorry about that. This happened in the Saclay mocks right?  Can you point me to a small transmission file that I can use to include it in the travis tests, so that we make sure quickquasars always run in those mocks? I can include that while fixing this bug. Thanks

**Comment by TEtourneau** [comment]
Yes, it's for Saclay Mocks, I was just analysing some test mocks.
You can find one of the latest transmission files we produced here: 
/global/projecta/projectdirs/desi/mocks/lya_forest/develop/debug/256-256-1536/mock_7/output/17/1747/transmission-16-1747.fits
This is from test mocks, so nothing too physical here, but I guess it doesn't matter since it's only to test the format. 
Thanks !

**Comment by sbailey** [comment]
@TEtourneau please run the following so that we can see those files:
```
chgrp -R desi /global/projecta/projectdirs/desi/mocks/lya_forest/develop/debug/256-256-1536
```
@alxogm when you have access to these files, please trim an example to as small as possible (e.g. just a few rows, perhaps even smaller than the smallest example file here) before adding to Travis testing.

**Comment by TEtourneau** [comment]
I already ran the command: chgrp -R desi /global/projecta/projectdirs/desi/mocks/lya_forest/develop/debug/256-256-1536/mock_7/output/ 
before sending the previous message. And I see the file in desi group:
-rw-rw---- 1 tetourne desi 86M Oct  4 07:30 debug/256-256-1536/mock_7/output/17/1747/transmission-16-1747.fits

Anyway, I just ran chgrp -R desi /global/projecta/projectdirs/desi/mocks/lya_forest/develop/debug/256-256-1536
Tell me if it's still not working

**Comment by alxogm** [comment]
I can see it now. thanks

**Comment by sbailey** [comment]
@TEtourneau thanks.  Your previous command got the ownership correct for the lower level files, but the upper level `256-256-1536` directory was still only readable by you so we couldn't see the other files/directories under it.

@alxogm we hope to make new tags very soon, but likely won't finish testing before Monday so if you can get the updated code + tests in my Monday noon, we can likely include them.  Thanks.
