### ISSUE TITLE
quickquasar produces different quasar catalog

### ISSUE THREAD

**Issue by londumas** [desihub/desisim#440]
For a given mocks seed, we should have the same output quasar catalog. For example,
`/project/projectdirs/desi/mocks/lya_forest/london/v4.0.0/quick-0.0/zcat.fits` should be the same as
 `/project/projectdirs/desi/mocks/lya_forest/london/v4.0.0/quick-2.0/zcat.fits`
@andreufont, do you know what is happening?

**Comment by andreufont** [comment]
Aren't these runs from different versions of quickquasars / desisim? If so, it is not strange that they have different quasar catalogs, isn't it?

**Comment by londumas** [comment]
Do you agree that within a given mock, for example v4.0.0, all different quickquasar production, should have the same redshift catalog, magnitude, ...
The effect of the different options of quickquasar will be on metals or no metals, on DLA or no DLA, on adding redshift errors...

**Comment by londumas** [comment]
@alxogm, Thanks. It works.
