### ISSUE TITLE
quickquasars: Add systematic redshift error

### ISSUE THREAD

**Issue by londumas** [desihub/desisim#442]
In table 4 of du Mas des Bourboux et al 2017 (https://arxiv.org/pdf/1708.02225.pdf), we have:
Delta r_parallel = −0.93 ± 0.14 Mpc/h.
This translates into a ~100km/s shift of the redshift along the line-of-sight.
It would be nice to add this to quickquasar.

**Comment by andreufont** [comment]
Yes, this should be trivial to add.

**Comment by alxogm** [comment]
@londumas Should this shift be added before generating the template?   Right now is only added at the very end, when writing the zbest file. 

Also, I imagine this should not affect the addition of DLAs/BALs metals, etc., right?

**Comment by andreufont** [comment]
@alxogm - I believe it comes from the way we measure the redshift with redrock, not something "real". Therefore I would add it at the last step, just like we do with sigma_z_fit. 

@londumas, do you agree?

**Comment by londumas** [comment]
@andreufont and @alxogm, yes I agree.
This feature should not be added to the spectrum. The wavelength solution of the BOSS and DESI spectrograph are very good. If there is a shift because of it it should be very small.
The `Delta_r_parallel ~ 100 km/s` shift is an effect on the measured quasar redshift from redrock.
So:
- either the quick-quasar mocks go through redrock and then you don't add the gaussian statistical errors, neither the systematic shift
- or the quick-quasar mocks don't go through redrock and then you can add these two effects.

Was-I clear enough @andreufont and @alxogm?

**Comment by andreufont** [comment]
I agree with what you say above @londumas.

**Comment by alxogm** [comment]
Yes, I just wanted to be sure. 
Thanks

**Comment by londumas** [comment]
@alxogm, Seems to be fixed. Can we close?
