### ISSUE TITLE
Apply dust extinction on simulated spectra

### ISSUE THREAD

**Issue by julienguy** [desihub/desisim#445]
Need to apply dust extinction on simulated spectra.
We currently have an inconsistency in the sims. The ETC adds extra exposure time based on the E(B-V),
but the extinction is not applied to the spectra!

**Comment by moustakas** [comment]
This is a duplicate of https://github.com/desihub/desitarget/issues/284 and is awaiting https://github.com/desihub/desispec/issues/513.

**Comment by julienguy** [comment]
Thanks John. I suggest we let this ticket open until it is resolved in desitarget.

**Comment by moustakas** [comment]
Done in https://github.com/desihub/desitarget/pull/425.
