### ISSUE TITLE
quickquasars should add FoG effect to the quasar redshift before generating templates

### ISSUE THREAD

**Issue by andreufont** [desihub/desisim#447]
Right now we are reading quasar redshifts from the transmission files, and use these to generate the random quasar continua. 

Later on, we add a random Fingers of God (FoG) correction to the quasar redshift, but this shift is not applied to the quasar continua. 

This is probably not a large effect for things like BAO, but if some is trying to use the synthetic spectra to generate composite quasar spectra, the noise in the composite will  be large underestimated. 

Note that this should not apply to the "redshift fitting error", since this should not modify the "true quasar spectrum", only our fake measurement of its redshift. 

This is marginally related to issues #441 and #442. It is not a priority either, I'm just putting it here so that we do not forget about it.

**Comment by alxogm** [comment]
Hi @andreufont so I moved the code to add the random FoG correction to quasar redshift before generating the template 
See [ #L399](https://github.com/desihub/desisim/blob/20ae01f46b94e424b4b86bb46a3574b2e31f01f3/py/desisim/scripts/quickquasars.py#L399)

This is also affecting the addition of BALs. I haven't tested if the effect is large, but probably is best to use the no_FOG redshift right for the addition of BALs? 

thanks 
alma

**Comment by andreufont** [comment]
@alxogm - It looks good. Why do you say we should use the no_FOG for the BALs? I would consider that the true redshift of the quasar, the one we would have if we had perfect N-body simulations, would be z + dz_fog, so that is the one I would use.

**Comment by alxogm** [comment]
@andreufont, I was confused on whether it should affect the inclusion of all DLAs, BALs, metals... and the shift we are adding in #442 (which we clarified)

If considered as the "true redshift" then I'll move this lines  to use it everywhere [#L250](https://github.com/desihub/desisim/blob/20ae01f46b94e424b4b86bb46a3574b2e31f01f3/py/desisim/scripts/quickquasars.py#L250)

do you agree?

**Comment by andreufont** [comment]
Yes, I would add it right before that line.

**Comment by londumas** [comment]
@alxogm, Seems to be fixed. Can we close?
