### ISSUE TITLE
check in the v3.1 basis templates

### ISSUE THREAD

**Issue by moustakas** [desihub/desisim#460]
This issue is to track the `v3.1` basis templates, which should get into the `18.12` software release to make full use of the improvements in https://github.com/desihub/desitarget/pull/427 and #453.

The current version of these new (`v3.1`) templates are in https://desi.lbl.gov/svn/data/basis_templates/trunk and I'm not expecting to make any more changes.  However, we may want to make sure https://github.com/desihub/desispec/issues/724 doesn't need any changes or other features before we cut a tag (which I don't think it will).

**Comment by sbailey** [comment]
I have vetted that https://desi.lbl.gov/svn/data/basis_templates/trunk works for the integration test from simulating targets through flux calibration and fitting redshifts.  OK to proceed with tagging basis_templates 3.1.

**Comment by moustakas** [comment]
Heads up, @sbailey:

The `stdstar_templates_v2.2.fits` file you created is missing the HDU names `FLUX` and `WAVE` for HDUs zero and two, respectively, which I made a mandatory part of the data model back in `v2.6`, and so `desisim-testdata/bin/trim_basis_templates` is crashing.  

I'll add a work-around in code for now (since I've already tagged `v3.1` in svn) but we should address this when we revisit https://github.com/desihub/desispec/issues/724.

**Comment by moustakas** [comment]
The `v3.1` tag has been created at
https://desi.lbl.gov/svn/data/basis_templates/tags/v3.1/
and the "lite" test templates were checked into 
https://github.com/desihub/desisim-testdata/pull/14

Begging forgiveness in advance, I'm going to update `desisim/.travis.yaml` (to use `DESISIM_TESTDATA_VERSION=master`, although we should make a tag) and `desisim/etc/desisim.module` to use the `v3.1` basis templates (which I'm updating at NERSC right now).

@sbailey You need to update `desimodules` (I think) at NERSC to incorporate this change, too.

**Comment by sbailey** [comment]
Thank for making the basis_templates/v3.1 tag.  I've updated the master installations at NERSC to use basis_templates/v3.1, made a new desisim-testdata/0.6.1 tag (desisim-testdata/master had been updated to match basis_templates/v3.1), and opened a PR #464 for desisim to use that version for testing.

**Comment by weaverba137** [comment]
@moustakas, At least some of the files are world-readable and don't need to be.  Also, is that really a checkout, or is it an export?  If it were a checkout, there should be a .svn directory somewhere.
