### ISSUE TITLE
Add dust-extinction in quickquasar

### ISSUE THREAD

**Issue by londumas** [desihub/desisim#468]
Add dust-extinction in quickquasar by default, to simulated data coming from desi.
The desi data will not be corrected for dust-extinction.

**Comment by moustakas** [comment]
In case it's helpful, we do this in `desitarget.mock.mockmaker` [here](https://github.com/desihub/desitarget/blob/master/py/desitarget/mock/mockmaker.py#L298-L312) and [here](https://github.com/desihub/desitarget/blob/master/py/desitarget/mock/mockmaker.py#L1038-L1039).

**Comment by alxogm** [comment]
Thanks @moustakas. It is very helpful, I'm working in it...

**Comment by alxogm** [comment]
Sorry for the delay, I've missed to comment the progress on this. I've tried to follow the way it is done in desitarget.mockmaker.  See https://github.com/desihub/desisim/compare/qquasar_extintion
I add here a couple of plots, of the simulated spectra with and without extinction, and the result on the 1D CF... @londumas  you might have a best feeling of whether the change is as expected...   should I do the 3DCF?  I'm not making a PR yet

![Screen Shot 2019-03-15 at 11 03 00 AM](https://user-images.githubusercontent.com/14896082/54449266-4f2fe380-4713-11e9-8538-176cb793d94a.png)
![Screen Shot 2019-03-15 at 11 13 16 AM](https://user-images.githubusercontent.com/14896082/54449294-5d7dff80-4713-11e9-9e5a-ffea8a2d1679.png)
![Screen Shot 2019-03-15 at 11 13 12 AM](https://user-images.githubusercontent.com/14896082/54449296-5f47c300-4713-11e9-937c-9b8932e6b424.png)

**Comment by alxogm** [comment]
@londumas I also wanted to ask if this option should apply when --eboss is used ?

**Comment by londumas** [comment]
@alxogm, thanks for doing that. Looks good. I don't think we need to look at the 3d correlation. And yes, we need this option for all type of surveys. Simply add something like `--dust-extinction`.

**Comment by londumas** [comment]
@alxogm, can we close as fixed? I think you did all this job.

**Comment by alxogm** [comment]
yes, lets close it. we'll rise a new issue if something comes up. Thanks

**Comment by andreufont** [comment]
I'd add some documentation on this on a wiki, so that we don't forget how it works in the future. We had lots of dicussions on GitHub, but it would be really useful to document them somewhere more permanent. May be even present the changes at a telecon, explaining the different options, and looking for a volunteer to look at the effect of the varying extinction on the 3D clustering. 

Some inspiration: https://arxiv.org/abs/1705.03190
