### ISSUE TITLE
difference in realization of the noise in quickquasar

### ISSUE THREAD

**Issue by londumas** [desihub/desisim#484]
Comparing two different runs of quickquasar using the same seed but one different option, I get some difference in the realization of the noise and of the continuum. I compare here:
 - /project/projectdirs/desi/mocks/lya_forest/london/v6.0/v6.0.0/eboss-0.0
 - /project/projectdirs/desi/mocks/lya_forest/london/v6.0/v6.0.0/eboss-0.2 (same as before, but adding `--dla file"`)

My plan is to first see if sending quickquasar with the same options allow to recover exactly the same results, then I will dig around. Maybe it is linked to the tails of the DLA, but I don't really believe it.
Thanks for the idea of looking at this @andreufont 

![flux](https://user-images.githubusercontent.com/3166436/55480651-036bae00-55de-11e9-9147-4869bc708b40.png)

![ivar](https://user-images.githubusercontent.com/3166436/55480652-036bae00-55de-11e9-93b1-6a1f6ccb9cd3.png)

```
flux = {'Mock0':{}, 'Mock1':{}}
flux['Mock0']['PATH'] = mock0['mock_base']+mock0['quick_ver']+'/spectra-16/0/0/spectra-16-0.fits'
flux['Mock1']['PATH'] = mock1['mock_base']+mock1['quick_ver']+'/spectra-16/0/0/spectra-16-0.fits'

for el in flux.keys():
    h = fitsio.FITS(flux[el]['PATH'])
    flux[el]['RA'] = h['FIBERMAP']['TARGET_RA'][:]
    flux[el]['DEC'] = h['FIBERMAP']['TARGET_DEC'][:]
    flux[el]['TARGETID'] = h['FIBERMAP']['TARGETID'][:]
    for ell in ['B','R','Z']:
        flux[el][ell+'_WAVELENGTH'] = sp.log10(h[ell+'_WAVELENGTH'].read())
        flux[el][ell+'_IVAR'] = h[ell+'_IVAR'].read()*(h[ell+'_MASK'].read()==0)
        flux[el][ell+'_FLUX'] = h[ell+'_FLUX'].read()
    h.close()

    
print( ((flux['Mock1']['B_WAVELENGTH']-flux['Mock0']['B_WAVELENGTH'])!=0.).sum() ) 
print( ((flux['Mock1']['R_WAVELENGTH']-flux['Mock0']['R_WAVELENGTH'])!=0.).sum() )
print( ((flux['Mock1']['Z_WAVELENGTH']-flux['Mock0']['Z_WAVELENGTH'])!=0.).sum() )

for i in range(10):
    
    snr = (flux['Mock1']['B_FLUX'][i]*sp.sqrt(flux['Mock1']['B_IVAR'][i])).mean()
    if snr<5.:
        continue
    print(snr)
    
    for ell in ['_IVAR','_FLUX']:
        for el in ['B','R','Z']:
            #plt.plot(flux['Mock1'][el+'_WAVELENGTH'],flux['Mock0'][el+ell][i])
            #plt.plot(flux['Mock1'][el+'_WAVELENGTH'],flux['Mock1'][el+ell][i])
            plt.plot(flux['Mock1'][el+'_WAVELENGTH'],flux['Mock1'][el+ell][i]/flux['Mock0'][el+ell][i])
        plt.xlabel( 'lambda_obs [A]' ) 
        plt.ylabel( (ell).replace('_','')+' ratio' ) 
        plt.grid()
        plt.show()
```

**Comment by andreufont** [comment]
Hi @londumas , I don't think this looks too bad... in the sense that there are very flat regions, meaning that the random seeds in the noise are probably the same. 

The spikes are just (hopefully) caused by the presence of the DLAs, it would be great to overplot the center of the DLAs in that plot, just in case. 

The reason there are broadband terms is because we enforce the spectrum to have a given magnitude, so if we remove flux near the DLA, we have to add it somewhere else. I'm not sure this explains all the differences, but it is something to take into account.

**Comment by alxogm** [comment]
@londumas I think the spikes are caused by the (small) flux values, if you plot the difference instead of ratio should look better.  At least it did when we look at that at some time ago, we were having  same issue, I think it was @andreufont who noted that at that point...

**Comment by londumas** [comment]
@andreufont and @alxogm, actually if I send the following, with and without DLA and ech twice I see exactly no difference. So it is possible that I updated desisim to the latests branch between `eboss-0.0` and `eboss-0.2`, and somehow we got differences in the noise realization.
```
quickquasars -i ../../0/0/transmission-16-0.fits --nproc 1 --outdir ./spectra-16_real0 --zbest --bbflux --eboss --seed 331116291 --sigma_kms_fog 0. --zmin 1.8 --metals LYB
quickquasars -i ../../0/0/transmission-16-0.fits --nproc 1 --outdir ./spectra-16_with_DLA_real0 --zbest --bbflux --eboss --seed 331116291 --sigma_kms_fog 0. --zmin 1.8 --metals LYB --dla file
quickquasars -i ../../0/0/transmission-16-0.fits --nproc 1 --outdir ./spectra-16_real1 --zbest --bbflux --eboss --seed 331116291 --sigma_kms_fog 0. --zmin 1.8 --metals LYB
quickquasars -i ../../0/0/transmission-16-0.fits --nproc 1 --outdir ./spectra-16_with_DLA_real1 --zbest --bbflux --eboss --seed 331116291 --sigma_kms_fog 0. --zmin 1.8 --metals LYB --dla file
```

![diff](https://user-images.githubusercontent.com/3166436/55496186-ac74d180-55fb-11e9-8547-cf08a34d9b67.png)
