### ISSUE TITLE
Put new BAL templates file into templates hierarchy

### ISSUE THREAD

**Issue by paulmartini** [desihub/desisim#487]
I have created a new BAL templates file: BAL-templates-v0.3.fits. The file is presently in moustakas's scratch space. Please incorporate this into the templates hierarchy. 

The new templates file includes more information about the properties of the BALs, such as BI, AI, and velocity range(s) for the troughs. The values are from Guo & Martini (2010). I also removed several marginal templates.

**Comment by moustakas** [comment]
Done in #513.
