### ISSUE TITLE
BAL templates used are not the most up to date

### ISSUE THREAD

**Issue by jfarr03** [desihub/desisim#509]
I've recently been running quickquasars and found that it is using templates from `/global/project/projectdirs/desi/spectro/templates/basis_templates/v3.1/bal_templates_v2.1.fits` when adding BALs, rather than the new `bal_templates_v3.0.fits` file (as mentioned in #504). 

Is this a deliberate choice? Or should it automatically use the most recent version? I think the relevant function is `io.find_basis_template`, which says that it should `Return the most recent template in $DESI_BASIS_TEMPLATE/{objtype}_template*.fits`, but I guess that it might not do so in this case as yet (potentially related to #504?).

**Comment by moustakas** [comment]
@jfarr03 Apologies, I have not had a chance to update and tag the basis templates with the new BAL templates.  I'll do so as soon as NERSC is back online but feel free to ping me again!

**Comment by jfarr03** [comment]
@moustakas No worries! I wasn't sure if this was a related issue as it seemed like `io.find_basis_template` was just selecting v2.1 as it came up last in the list of BAL template files when it searches with `glob`, but I guess this could have something to do with the tagging etc.

**Comment by moustakas** [comment]
Done in #513.

**Comment by jfarr03** [comment]
Thanks for this @moustakas, much appreciated!
