### ISSUE TITLE
desisim version mismatch

### ISSUE THREAD

**Issue by weaverba137** [desihub/desisim#51]
0.7 has been tagged but the ``__version__`` string is still 0.6.dev1.

**Comment by weaverba137** [comment]
This was fixed by PR #55.

**Comment by weaverba137** [comment]
This is *still* a problem!  Right now the `__version__` string is 0.7.dev287, but we're already on the 0.8 series of tags.

**Comment by cballand** [comment]
Version mismatch solved in PR #63
