### ISSUE TITLE
Remove sncosmo from transients or make it a weak dependency.

### ISSUE THREAD

**Issue by sybenzvi** [desihub/desisim#524]
The [sncosmo](https://sncosmo.readthedocs.io/) package should be a weak dependency of desisim or be removed entirely. Currently affects just the transients branch.

**Comment by sbailey** [comment]
Agreed.  At worst it should only be required if executing a transients-specific function that uses sncosmo code.  It should not be required to import any desisim code.  i.e. any sncosmo imports should be "hidden" inside functions, not at the top level of modules.

**Comment by sybenzvi** [comment]
The sncosmo import is now protected by a try/except block. If a user hasn't installed sncosmo the transients submodule will still be loaded but none of the models depending on the sncosmo package will appear in the transient model registry. It should be transparent for end users.
