### ISSUE TITLE
Update BAL metadata in quickquasars (and probably select_mock_targets) 

### ISSUE THREAD

**Issue by alxogm** [desihub/desisim#526]
This raises from discussion in the #tucson2020_hack_bal in slack. The summary from @andreufont  is copied here 

> Which are the potential uses of the BAL meta data?
> Non-picca tests: for instance, effect of BALs in redrock fitter. For this it would be good if all BAL meta data was contained in the truth file, one per HEALPix pixel like we are doing now. 
> Picca tests: which spectra need to be masked, and how much. This requires a single “BAL catalog” file, containing all information for all quasar spectra. 
> 
> When we run quickquasars, we do it one HEALPix pixel at a time, and we output the mock spectra files and the truth files. These outputs are enough for the “non-picca” tests discussed above.
> 
> At the end of all the quickquasars runs, we have to run a few post-process steps to construct the mock “quasar catalog” file, and it is in this step when we would also run the mock “BAL catalog” file. This is the file needed for the tests involving Picca.
> 
> Open questions:
> A) How much meta-data should we put into the truth files? Should it go into the main TRUTH extension, QSO_META or BAL_META?
> B) How much meta-data should go into the BAL catalog file? How do we construct it?
> 
> Suggested answers:
> A) Even though BALTEMPLATEID could be enough, it would be convenient if users did not have to look for the template info into a different file, and had all relevant data in the same truth file. 
> I’d advocate that all the BAL meta-data should be included into the truth files, in a separate HDU named BAL_META that would only exist if the mocks were run with --balprob larger than 0. If not, that HDU would not exist.
> I would be generous here, and add all possible BAL information, like the information that Paul has added to the baltruth files.
> I would not add any BAL meta-data into the main TRUTH extension (HDU), since when running non-quickquasars runs (full survey sims) some of the objects will not even be quasars.
> We could consider having some BAL-related metada in the QSO_META extension (HDU), but I’m not convinced there is much point in having duplicated BAL information in the both HDUs. Happy to discuss. We'll have this discussion in github when updating the metadata in quickquasars. 
> B) I would add all the information that Paul has added to the baltruth files. Ideally, we would have a single script (either in desisim or in Picca) that looks for all the truth files that went into the making of the mock, and collects all relevant meta data  from the BAL_META extensions.

1) I think we all agree with response A, so I'll start by changing the metadata [here](https://github.com/desihub/desisim/blob/7b9207638d289ad316642d77f9eeeb75a7fb8227/py/desisim/io.py#L942 ) and [here](https://github.com/desihub/desisim/blob/7b9207638d289ad316642d77f9eeeb75a7fb8227/py/desisim/io.py#L980) To save more than  it is now. Then from quickquasars I'll keep only the metadata columns that match with the BAL catalog example provided by @paulmartini . Alternatively I can leave the mentioned line as it is, and retrieve the data only from quickquasars to recover the data we want. 

2) The remaining question is if we keep some BAL-related metadata in the QSO_META extension. I'd say yes to keep the same format as in select_mock_targets (where we don't have additional HDUs for BALs/DLAs). But it could also be, that we change select_mock_targets to also have independent HDU extensions for BAL and DLA metadata, which is easy to do... but I'm not sure is what we want, given that tests at individual pixels are easier to do in quickquasars and once everything works there, will work the same I select_mock_targets.... @andreufont  @moustakas @paulmartini  any comment here? 

3) Names of HDU extensions: I'll replace 'QSO_META' ---> 'TRUTH_QSO', to have the same name in quickquasars and select_mock_targets.

**Comment by alxogm** [comment]
So I worked a bit on this, and pushed a branch https://github.com/desihub/desisim/compare/BAL_META, not a PR yet. 

I have some points (questions) to discuss. 

1) Trying to add more information to the BAL_META I found it was easier that the function [desisim.bal.insert_bals](https://github.com/desihub/desisim/blob/e94ccc994fca2047a59035735e8bc8dfc0e4d2f2/py/desisim/bal.py#L149) returns the metadata of only BAL qso's, than return a metadata table for all qsos's and trimmed it to only BALs in quickquasars afterwards. This will break select_mock_targets as it is now but is very easy to fix). I'm not aware of other things that can be broken, what do think @moustakas ? I have an alternative that only involves modifying quickquasars, but I like more this one... so please let me know your thoughts. 

2) With changes described in 1, we can now save the BAL_META  that resembles Paul's BAL catalog example. @paulmartini I only have a couple of questions about whether we need to save the redshift here, since it is the TRUTH HDU,  and if you have a strong preference for  'BALTEMPLATEID' over  'BAL_TEMPLATEID' (The second one was used originally in the BAL_META)... Thanks.  

Now the next point is about question B, and comments, in the summary above. 

1) From what I've worked in select_mock_targets, I think it would be better to keep the truth format as it is. i.e. it only saves the BAL_TEMPLATEID for BALS, and whether a qso has DLA or not. With this it is easy to recover all extra information to construct truth BAL/DLA catalogs. I don't think we will be doing much tests on individual pixels (point A in the summary A), at least not in the short term. Therefore at least for now I would not add additional HDUs for the BAL/DLA metadata in the truth files generated by select_mock_targets.
If you agree with that, we still would like that quickquasars and select_mock_targets truth files are alike in the extensions that are common to both. Therefore in quickquasars I would save the  BAL_TEMPLATEID in the TRUTH_QSO extension (HDU), even when we have such information in the BAL_META. I would the same thing for DLAs.  What do you think @andreufont @moustakas ?

2) It might be useful that the addition of the BAL/DLA HDUs to the truth files is optional. We agree it is useful for tests on individual pixels (as explained in the summary), but for production we will likely use only the final BAL/DLA catalogs, and if more information is needed we can always recover it since it will be present in the TRUTH_QSO HDU. @andreufont what do you think? I'd be  adding an argument to test this (--meta )

I'll make the PR after your feedback, in case I need to do major revisions :D

Many thanks for your comments!

**Comment by andreufont** [comment]
If possible, I'd try to have the same structure in mocks generated with select-mock-target than mocks generated with quickquasars. I think it will make life easier for those reading mocks from both simulations (quasar classifiers, redshift fitters...). If it gets too complicated, we can leave with different strucutres, but then we would need to document all this very well.

For instance, if we think we need a BAL/DLA extension when running quickquasars, I'd imagine we would also need it in select-mock-target. But it is not clear we need it, it might be enough to add all BAL-related metadata in the TRUTH_QSO extension, I don't know. 

I'm not too worried about using too much space or time writing the meta-data, so I don't think we need it to be an option to print it or not. I'd print it always, it should have a negligible impact in performance, isn't it?

**Comment by alxogm** [comment]
Hi @andreufont,  I'll try to see the select_mock_targets counterpart soon. I'm sure is doable given the structure, but I'd like to solve a couple of other issues I have open first. 

I'll make this PR on quickquasars during the weekend and I'll re-run one of the small tucson2020_hack_bal to check it all runs ok.

**Comment by andreufont** [comment]
Sounds good!

**Comment by paulmartini** [comment]
I think this overall sounds good. I was a little concerned about having separate BAL catalogs for redrock and picca, but since these are for mocks, then the two catalogs could presumably be generated at the same time and would have the same data. 

For what it is worth, my experience with BAL masking so far is that we are using only as subset of the data in the catalogs (AI, BI, VMIN, VMAX) and not other information (POSMIN, FMIN), so if there were space concerns, we could probably get away with a 'light' version of the catalogs. But it seems space/performance is not really an issue. And it seems valuable to have the same format as the observed catalogs. Speaking of which, I'd appreciate feedback on that format. 

Also, I don't have a strong opinion about BAL_TEMPLATEID vs. BALTEMPLATEID. 

Sorry for the slow response.

**Comment by alxogm** [comment]
Hi @paulmartini, thanks for looking into it.  

>  I was a little concerned about having separate BAL catalogs for redrock and picca, but since these are for mocks, then the two catalogs could presumably be generated at the same time and would have the same data.

sorry, I don't follow this comment... do you mean a BAL catalog for masking the BALs and try to redo the redshift fit with redrock? Why do you said this would not be the same that the one used for picca? 

thanks. 

Ps. if there is no concern about names then I'll leave  BAL_TEMPLATEID.

**Comment by paulmartini** [comment]
Hi @alxogm, 

This comment was to agree with @andreufont's comment above that for non-picca tests (e.g. redrock) it would be good if all BAL meta data were in a truth file, one per HEALPix pixel, while picca tests would be easier to do with a single BAL catalog.  

Paul
