### ISSUE TITLE
desisim sky level test failure

### ISSUE THREAD

**Issue by moustakas** [desihub/desisim#534]
Opening a ticket for an issue sent by @sbailey on-list:

```
Something late last week changed that started breaking this test:

======================================================================
FAIL: test_newexp_sky (desisim.test.test_obs.TestObs)
Test different levels of sky brightness
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desisim/master/py/desisim/test/test_obs.py", line 127, in test_newexp_sky
    self.assertTrue(np.all(sky_mws[nonzero] > sky_dark[nonzero]))
AssertionError: False is not true

Does anyone recognize what might have caused that?  Running "python py/desisim/test/test_obs.py" 
can confirm that without having to run all the other tests.

    it fails when using master of everything
    it fails when using master of everything except desisim/0.34.2 (used in the 19.12 software release)
    it passes when using the full suite of tags for 19.12

Adding to the mystery, there seems to be a clear bug in test_obs.py lines 119-122:

        sim_dark, fmap_dark, meta_dark, obscond_dark, objmeta_dark = obs.new_exposure('dark', nspec=10, night=night, expid=0, exptime=1000)
        dark = sim_dark.simulated.copy()
        sim_mws, fmap_mws, meta_mws, obscond_mws, objmeta_mws = obs.new_exposure('mws', nspec=10, night=night, expid=1, exptime=1000)
        mws = sim_dark.simulated.copy()

Note that "mws" is copying from sim_dark instead of sim_mws, so I don't see how the 
later test that the mws sky brightness > the dark sky brightness could have passed, 
unless they were all zeros which also seems unlikely.



```

**Comment by moustakas** [comment]
The failure is coming from the fact that the simulated sky spectra are *negative* (in units of electrons).

<img width="571" alt="Screen Shot 2020-05-07 at 8 28 27 AM" src="https://user-images.githubusercontent.com/1431820/81294433-e5704880-903c-11ea-9282-1866bb4c6f31.png">

**Comment by moustakas** [comment]
I tried to track this issue down into `specsim` but wasn't successful. As far as I can tell, the sky spectra are negative when they leave `simexp.simulate_spectra` but I can't quite track down where in `specsim.simulator.Simulator.simulate` this is occurring. 

@dkirkby @julienguy any suggestions? And can you confirm that the simulated sky spectra (in this case, `num_sky_electrons_z` should *not* be negative (i.e., they don't include Poisson noise)?

**Comment by moustakas** [comment]
Here's a very simple MWE based on the unit test:
```
import numpy as np
from desisim import obs
sim_mws, fmap_mws, meta_mws, obscond_mws, objmeta_mws = obs.new_exposure('mws', \
  nspec=10, night='20150101', expid=1, exptime=1000)
assert(np.all(sim_mws.simulated['num_sky_electrons_z'] >= 0))
```

**Comment by dkirkby** [comment]
specsim takes a tabulated sky surface brightness as input and propagates it to a mean expected number (without any shot noise added) of detected electrons due to sky (per wavelength bin) in each camera.  A positive input surface brightness should never result in a negative output `num_sky_electrons_z`.

It sounds like something in desisim is feeding a negative surface brightness into specsim, either via the initial spectrum or the modifications due to extinction and moon.  You should be able to confirm this by adding these asserts to this function in `specsim/atmosphere.py`:
```
    @property
    def surface_brightness(self):
        """astropy.units.Quantity: Total sky surface brightness.

        Includes both dark sky emission and (if configured) scattered moonlight.
        Changes to :attr:`condition` or :attr:`airmass` are reflected here.
        """
        sky = self._surface_brightness_dict[self.condition].copy()
        assert np.all(sky >= 0), 'Input sky has negative values for ' + self.condition
        if self._extinct_emission:
            sky *= self.extinction
            assert np.all(sky >= 0), 'Sky extinction has negative values'
        if self.moon is not None and self.moon.visible:
            sky += self.moon.surface_brightness
            assert np.all(sky >= 0), 'Moon contribution is negative'
        return sky
```

**Comment by dkirkby** [comment]
I should add that `num_sky_electrons_z` is not one of the specsim output columns (documented [here](https://specsim.readthedocs.io/en/stable/output.html#camera-output-tables)) so it's possible that the code which generates this column is doing more than just copying the specsim z-band `num_sky_electrons` values.

**Comment by sbailey** [comment]
A few more data points: I inspected variables after the call to `specsim.simulator.Simulator.simulate` (`desi.simulate`) on [simexp.py L585](https://github.com/desihub/desisim/blob/c405acdc65e9d8d3f1e5170f2ce59ca395f8def2/py/desisim/simexp.py#L585).  The input flux and atmosphere surface brightness are positive, but the outputs num_sky_electrons have negative values:
```
In [35]: np.all(flux>=0)                                                        
Out[35]: True

In [36]: np.all(desi.atmosphere.surface_brightness>=0)                          
Out[36]: True

In [37]: np.all(desi.simulated['num_sky_electrons_z']>=0)                       
Out[37]: False
```

I remain confused, however, since we've been using simpsec tag v0.13 since January, and the section of simexp.py that uses it was last updated years ago (though a more recent change added freeze_iers, but I don't see how that could have an impact).  And the astropy units stuff @moustakas has been chasing seems to be an effect of newer versions of astropy, not the ancient 2.0.14 that we're using at NERSC (and which previously worked).

**Comment by moustakas** [comment]
I confirmed that, internally to `specsim`, the sky spectrum in units of photons is all positive while the same spectrum in units of electrons has negative values:
https://github.com/desihub/specsim/blob/master/specsim/simulator.py#L495-L496

The only difference is the multiplication of the throughput, which indeed has small, negative values:

```
camera.throughput[camera.throughput < 0]
array([-3.73877825e-07, -7.70440930e-07, -1.18731699e-06, -1.62213373e-06,
       -2.07251894e-06, -2.53610048e-06, -3.01050628e-06, -3.49336429e-06,
       -3.98230258e-06, -4.47494923e-06, -4.96893242e-06, -5.46188037e-06,
       -5.95142137e-06, -6.43518377e-06, -6.91079599e-06, -7.37588650e-06,
       -7.82808383e-06, -8.26501659e-06, -8.68431345e-06, -9.08360312e-06,
       -9.46051439e-06, -9.81267612e-06, -1.01377172e-05, -1.04332667e-05,
       -1.06969535e-05, -1.09264068e-05, -1.11192557e-05, -1.12731296e-05,
       -1.13856575e-05, -1.14544690e-05, -1.14771935e-05, -1.14514603e-05,
       -1.13748991e-05, -1.12451395e-05, -1.10598110e-05, -1.08165436e-05,
       -1.05129669e-05, -1.01467108e-05, -9.71540518e-06, -9.21668012e-06,
       -8.64816562e-06, -8.00749180e-06, -7.29228883e-06, -6.50018696e-06,
       -5.62881647e-06, -4.67580775e-06, -3.63879121e-06, -2.51539736e-06,
       -1.30325675e-06, -3.15341896e-17, -5.20399517e-06, -1.07237440e-05,
       -1.65262258e-05, -2.25784210e-05, -2.88473107e-05, -3.52998771e-05,
       -4.19031031e-05, -4.86239726e-05, -5.54294703e-05, -6.22865820e-05,
       -6.91622940e-05, -7.60235938e-05, -8.28374698e-05, -8.95709112e-05,
       -9.61909080e-05, -1.02664451e-04, -1.08958533e-04, -1.15040145e-04,
       -1.20876283e-04, -1.26433940e-04, -1.31680111e-04, -1.36581794e-04,
       -1.41105985e-04, -1.45219683e-04, -1.48889886e-04, -1.52083595e-04,
       -1.54767811e-04, -1.56909535e-04, -1.58475769e-04, -1.59433518e-04,
       -1.59749786e-04, -1.59391578e-04, -1.58325900e-04, -1.56519760e-04,
       -1.53940166e-04, -1.50554127e-04, -1.46328652e-04, -1.41230753e-04,
       -1.35227440e-04, -1.28285727e-04, -1.20372628e-04, -1.11455155e-04,
       -1.01500326e-04, -9.04751561e-05, -7.83466622e-05, -6.50818626e-05,
       -5.06477763e-05, -3.50114231e-05, -1.81398237e-05])
```

**Comment by moustakas** [comment]
Here's the problem. It looks like the throughput tables in `desimodel/data/throughput` were updated recently, and for the z-band camera they contain the exact same number of small, negative values as we're seeing in the sky spectra that cause this unit test to fail:
```
(desi) ioannis@atlas:~/repos/desihub/desimodel/data/throughput% ls -l thru-*
-rw-rw-r--  1 ioannis  staff  1785600 May  7 05:44 thru-b.fits
-rw-rw-r--  1 ioannis  staff  1627200 May  7 05:44 thru-r.fits
-rw-rw-r--  1 ioannis  staff  1848960 May  7 05:44 thru-z.fits
(desi) ioannis@atlas:~/repos/desihub/desimodel/data/throughput% pwd
/Users/ioannis/repos/desihub/desimodel/data/throughput
(desi) ioannis@atlas:~/repos/desihub/desimodel/data/throughput% ipython
Python 3.8.1 | packaged by conda-forge | (default, Jan 29 2020, 15:06:10)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.12.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from astropy.table import Table

In [2]: tt = Table.read('thru-z.fits')
WARNING: hdu= was not specified but multiple tables are present, reading in first available table (hdu=1) [astropy.io.fits.connect]

In [3]: tt[tt['throughput'] < 0]
Out[3]:
<Table length=199>
    wavelength            throughput            extinction          fiberinput
     float64               float64               float64             float64
------------------ ----------------------- ------------------- -------------------
            7360.1 -1.8395497931257288e-07 0.06940299374193222 0.43087495964147715
 7360.200000000001  -3.738778248818205e-07 0.08302492247908168 0.43087543480842905
 7360.300000000001  -5.694719896667549e-07 0.13611887980683604  0.4308759099738493
7360.4000000000015  -7.704409304777918e-07 0.12915882672357926  0.4308763851377419
 7360.500000000002   -9.76488107978372e-07  0.0803125202943765  0.4308768603001106
 7360.600000000002 -1.1873169866865442e-06 0.07006890871995416  0.4308773354609593
 7360.700000000003 -1.4026310349765803e-06   0.068392916176107  0.4308778106202919
 7360.800000000003 -1.6221337250805784e-06 0.06884120179103896  0.4308782857781126
 7360.900000000003 -1.8455285330900574e-06    0.07599502025415 0.43087876093442506
 7361.000000000004  -2.072518938957555e-06 0.10169830173247145 0.43087923608923323
 7361.100000000004 -2.3028084264982215e-06 0.08809323433902334 0.43087971124254093
 7361.200000000004  -2.536100483391415e-06 0.06961109685901357  0.4308801863943523
 7361.300000000005 -2.7720986011822853e-06 0.06737083725913555   0.430880661544671
 7361.400000000005 -3.0105062752833696e-06  0.0700325464254122  0.4308811366935011
7361.5000000000055 -3.2510270049761737e-06   0.084535263274932  0.4308816118408464
               ...                     ...                 ...                 ...
 7388.400000000103 -0.00011145515548619085 0.06775279694036557 0.43100938537789696
 7388.500000000104 -0.00010660947201251015 0.07376445793164418 0.43100986026733223
 7388.600000000104 -0.00010150032624413722 0.07454015799520411  0.4310103351563419
 7388.700000000104  -9.612359523809135e-05  0.0673823417348589  0.4310108100449298
 7388.800000000105   -9.04751561082274e-05  0.0655426270770526 0.43101128493309976
 7388.900000000105  -8.455088602525406e-05  0.0650375108626113  0.4310117598208557
7389.0000000001055  -7.834666221674913e-05 0.06480666777973759  0.4310122347082017
 7389.100000000106  -7.185836196717742e-05 0.06493561554541304  0.4310127095951415
 7389.200000000106  -6.508186261790642e-05 0.06499582243707806   0.431013184481679
 7389.300000000107  -5.801304156722317e-05  0.0656083256541915  0.4310136593678182
 7389.400000000107  -5.064777627035105e-05 0.06965082462799063 0.43101413425356305
 7389.500000000107  -4.298194423946571e-05 0.07230504559412006 0.43101460913891726
 7389.600000000108 -3.5011423043712075e-05 0.06807308341132565   0.431015084023885
 7389.700000000108 -2.6732090309220403e-05 0.06736429794917496  0.4310155589084699
 7389.800000000108 -1.8139823719123232e-05  0.0661767990724025   0.431016033792676
 7389.900000000109  -9.230501013571074e-06 0.06592081022347977 0.43101650867650726
```

**Comment by moustakas** [comment]
Looks like https://github.com/desihub/desimodel/pull/137 and this change to `desimodel/data` may be related?
```
(desi) ioannis@atlas:~/repos/desihub/desimodel/data/throughput% svn log | head
------------------------------------------------------------------------
r131318 | dkirkby | 2020-04-16 20:11:28 -0400 (Thu, 16 Apr 2020) | 1 line

Merge branch update_inputs into trunk
```
I'm confused, though, because `desisim` Travis tests use the `branch/test-0.10` branch of `desimodel`, so presumably this failure should not have occurred (assuming the throughputs are all positive there). 

It makes sense that the unit tests would fail when running them on the command line (which is what I've been doing), because then the code would point to `desimodel/trunk`.

And indeed I will note that Travis tests for https://github.com/desihub/desisim/pull/536 did pass!

@sbailey how would you like to proceed?

**Comment by dkirkby** [comment]
Thanks for tracking this down @moustakas.  I will take care of clipping the small negative values in the latest update to the DESIMODEL throughputs (with another commit to desihub/desimodel#137), but that is still work in progress so should not be affecting the travis unit tests for desisim.

Note that [this travis test](https://travis-ci.org/github/desihub/desisim/builds/685028038) is still failing while using `DESIMODEL_DATA=branches/test-0.10` so presumably there is still a separate problem?

**Comment by moustakas** [comment]
> Note that this travis test is still failing while using DESIMODEL_DATA=branches/test-0.10 so presumably there is still a separate problem?

Hmm, that's #507 again. I'll dig.

**Comment by moustakas** [comment]
Fixed in #536.

**Comment by sbailey** [comment]
desimodel still has negative throughputs causing desisim test failures, so reopening this until it is fully resolved.  I'll ping desihub/desimodel#137 which is where I think the fix will happen.  @dkirkby @moustakas

**Comment by moustakas** [comment]
For the time being, could test against the previous `desimodel` branch, before the throughputs went negative.

**Comment by weaverba137** [comment]
Based on dates that I've seen so far, it looks like `desimodel/branches/test-0.12` might not contain the updated files that fix negative throughputs.  

When I ran a test on my laptop with desimodel/trunk, this particular test passed.

@sbailey, could you possibly create a test-0.13 branch?

**Comment by sbailey** [comment]
desimodel test-0.13 branch created, I think that addresses the testing issue.  Combined with Ben's tests passing with desimodel/trunk, and John's MWE now passing, I think this issue is resolved.  Closing ticket.
