### ISSUE TITLE
"Refraction model is inaccurate for altitudes below 5.0 deg" warning in test_quickquasars unit test

### ISSUE THREAD

**Issue by moustakas** [desihub/desisim#557]
Running 
```
python py/desisim/test/test_quickquasars.py
```
yields the following warning (in addition to https://github.com/desihub/specsim/issues/119):

```
[snip]
INFO:quickquasars.py:716:simulate_one_healpix: Dust extinction added
INFO:quickquasars.py:717:simulate_one_healpix: exposure time adjusted to 43393141.096335374
INFO:quickspectra.py:64:sim_spectra: Starting simulation of 4 spectra
DEBUG:simexp.py:418:simulate_spectra: loading specsim desi config desi
DEBUG:simexp.py:422:simulate_spectra: creating specsim desi simulator
/Users/ioannis/code/desihub/specsim/specsim/transform.py:593: UserWarning: Refraction model is inaccurate for altitudes below 5.0 deg.
  warnings.warn(
INFO:simexp.py:444:simulate_spectra: MJD not in obsconditions, using DATE-OBS 2009-06-18T12:00:00.000
DEBUG:simexp.py:448:simulate_spectra: obsconditions SEEING = 1.1
DEBUG:simexp.py:448:simulate_spectra: obsconditions EXPTIME = 43393141.096335374
DEBUG:simexp.py:448:simulate_spectra: obsconditions AIRMASS = 1.0
DEBUG:simexp.py:448:simulate_spectra: obsconditions MOONFRAC = 0.0
DEBUG:simexp.py:448:simulate_spectra: obsconditions MOONALT = -60
DEBUG:simexp.py:448:simulate_spectra: obsconditions MOONSEP = 180
[snip]
```

The clue is in the log output which digging confirms that the warning is caused by the 43 million second exposure time, `EXPTIME = 43393141.096335374`! Looks like this is happening here, where (in the test case) the dust correction to the exposure factor ends up being about 10^4:
https://github.com/desihub/desisim/blob/master/py/desisim/scripts/quickquasars.py#L714
```
    # Attenuate the spectra for extinction
    if not sfdmap is None:
       Rv=3.1   #set by default
       indx=np.arange(metadata['RA'].size)
       extinction =Rv*ext_odonnell(qso_wave)
       EBV = sfdmap.ebv(metadata['RA'],metadata['DEC'], scaling=1.0)
       qso_flux *=10**( -0.4 * EBV[indx, np.newaxis] * extinction)
       if fibermap_columns is not None:
          fibermap_columns['EBV']=EBV
       EBV0=0.0
       EBV_med=np.median(EBV)
       Ag = 3.303 * (EBV_med - EBV0)
       exptime_fact=np.power(10.0, (2.0 * Ag / 2.5))
       obsconditions['EXPTIME']*=exptime_fact
       log.info("Dust extinction added")
       log.info('exposure time adjusted to {}'.format(obsconditions['EXPTIME']))
```
I don't understand the factor of two in the exponent: shouldn't the factor just be `np.power(10.0, (Ag / 2.5))`?

In any case, the problem seems to be that for this test case, the coordinates of the simulated targets put them right smack in the disk of the Galaxy, and so the g-band extinction is upwards of 5 mag!
https://www.legacysurvey.org/viewer?ra=84.5542&dec=32.1582&layer=sfd&zoom=5
```
Table(metadata)
<Table length=4>
     RA         DEC             Z               Z_noRSD        MOCKID
  float64     float64        float64            float64        int64
----------- ----------- ------------------ ----------------- ---------
84.56347552 32.14649459 3.7875074541239577 3.785041570663452 310101303
88.25858593 26.61522843 3.1684850732812913  3.16990327835083 310118303
85.18114653 30.10225407 3.3774911599545714 3.372465133666992 310118306
84.04246538 32.34100748 3.6354410048293717 3.630274772644043 310118309
```

So I think everything is OK/correct except that factor of two in the dust correction factor is an error (or I'm missing something, which is entirely possible!).

Looks like @andreufont may have added these lines?
  https://github.com/desihub/desisim/blame/master/py/desisim/scripts/quickquasars.py#L703-L717

**Comment by andreufont** [comment]
Sorry, I know this is is urgent, but I can not look at it today / this week. 

Not sure if @alxogm might be able to help?

**Comment by alxogm** [comment]
Hi @moustakas,  I recall  I implemented these lines from https://github.com/desihub/desisurvey/blob/502d3b074babf30b504ee75cccf79b53e398e4dc/py/desisurvey/etc.py#L99 

(not sure at the moment if I check it was correct or only assumed it was :S)

**Comment by alxogm** [comment]
By the way, it was implement by request of Helion a while ago, but so far we haven't really used it. @andreufont we should discuss if we really need it or not.

**Comment by andreufont** [comment]
If we have not used this feature so far, and we have doubts whether it has an issue or not, maybe we could deprecate it and remove it from the tests. We could leave the code commented out, or similar, in case we want to reinstall it.

**Comment by moustakas** [comment]
OK, this issue is now fully understood and I'm planning to close it. Thank you for everyone's input.

First, all the code is correct, including the power of two in the exponent (the dust correction to the exposure time goes like the square of the dust column). This warning is caused by the fact that the London and Saclay Lya "skewers" we're using are right in the plane of the Galaxy, which leads to the ridiculous dust-corrected exposures times.

For the record, that region of the sky is being used because of the "mini" dust maps which are checked into the `desisim` repository (the same ones used for the `desiutil` unit tests). These maps consist of the first 10x10 pixels of the nominal SFD maps and happen to correspond to the part of the sky in the Galactic plane. I looked into how easy it would be to pull out a different piece of the map but it's not super-trivial to have it match the coordinates of the test skewers we're currently using.

So I don't think there's any reason to deprecate this test (even though this functionality isn't being used much) because everything is correct. We just need to remember that the warning, "Refraction model is inaccurate for altitudes below 5.0 deg" is just that, a warning and nothing to worry about.

**Comment by andreufont** [comment]
Sounds good. Thanks for the thorough investigation @moustakas and @alxogm !
