### ISSUE TITLE
objtype STAR vs. different flavors of stellar targets

### ISSUE THREAD

**Issue by crockosi** [desihub/desisim#64]
The template generator for STARs need to be a little more flexible to accept more flavors of STAR targets. For example, right now the input gmag distribution is used as the input WD mag distribution and the input rmag for the all other star templates.  Can all the target mag distributions be taken from targets.dat in desimodel?  Also, can we make the input flavor of star (WD, FSTD, MWS) and argument rather than individual true/false flags?  Right now the only way to specify sub-types is WD=True or FSTD=True. For example, I can imagine wanting to have multiple flavors of STAR_MWS so I can get different target cuts and even now the MWS wants a different range than the FSTDs, and I expect the BAD_QSO stars want yet a different mag distribution. 

Related, the same objtype used for magnitude limits and TS cuts is passed to specter/throughput.py and used to compute the fiber losses. It would be nice to be able to specify just "star" to specter, since it doesn't need more than that. Right now specter uses the "default input loss" and just generates a warning, but here as well it would be good to distinguish target type from object type. 

I'm happy to make these changes, but need input on where some of the default data (like color cuts) should go and  I don't want to give grief to all uses of FSTD=True code without warning.

**Comment by moustakas** [comment]
> The template generator for STARs need to be a little more flexible to accept more flavors of STAR targets. For example, right now the input gmag distribution is used as the input WD mag distribution and the input rmag for the all other star templates. Can all the target mag distributions be taken from targets.dat in desimodel? Also, can we make the input flavor of star (WD, FSTD, MWS) and argument rather than individual true/false flags? Right now the only way to specify sub-types is WD=True or FSTD=True. For example, I can imagine wanting to have multiple flavors of STAR_MWS so I can get different target cuts and even now the MWS wants a different range than the FSTDs, and I expect the BAD_QSO stars want yet a different mag distribution.

Thank you for taking a look @crockosi !  We began with very simple (i.e., flat) priors to get something in place but will certainly support more options, e.g., various input magnitude / redshift distributions, selection bands, color cuts, etc.  But let's start with supporting other types of stars.  How do you want to specify the spectral types?  I'm using Carlo's latest models, documented here:
  https://desi.lbl.gov/DocDB/cgi-bin/private/RetrieveFile?docid=870;filename=stellar-templates.pdf;version=1

The FSTD class is based on a simple selection in (DECaLS) grz color-color space:
  https://desi.lbl.gov/trac/wiki/TargetSelectionWG/STDalgorithms#ProposedgrzSelection

We could similarly define other spectral types in color-color space, or even in physical parameter (Teff, logg, [Fe/H]) space.  Please let me know what would add maximum flexibility for the MWS. (We can also take this off-list with a phone call if that'd be easier.)

**Comment by crockosi** [comment]
After some clarifying discussion with John, we propose the following:

1) make_templates in the STAR template class will now take an argument SUBTYPE which can be WD, FSTD, or any other flavor of stellar target.  This will replace the current boolean options for WD and FSTD.  Code in the body of make_templates can then invoke target cuts and sample the magnitude distribution as appropriate, and subtypes can be added without expanding the argument list. 
2) the "truth" dictionary returned by get_targets will also get a SUBTYPE entry where the information about the flavor of stellar target will be kept.  OBJTYPE will be STAR, and that information will be used to communicate point-source-ness and other properties of all stellar targets to e.g. specter so it doesn't have to be taught the name of every subtype of stellar target.

**Comment by dkirkby** [comment]
I agree that the current boolean options for WD, FSTD need to be updated, but I am less convinced that it makes sense to implement all the current and future stellar types in the same `templates.STAR` class, or to give these all `OBJTYPE=="STAR"`.  The other template classes (QSO, ELG, LRG) correspond to specific targeting classes with associated photometric cuts, and this is also (as far as I know) how we use `OBJTYPE` in (e)BOSS.  I have been thinking of `OBJTYPE` as one of the primary attributes used for analysis, in which case we could find a different mechanism for specter to identify psf-like sources.

Looking at the current `templates.STAR` class, I see some `if FSTD: ... elif WD: ...` logic that does not look like it will scale well to adding more stellar types.  A simple solution would be to define a `STAR` base class that does the common stuff like radial velocity redshifting, and subclass this for each type with its own targeting cuts.

**Comment by crockosi** [comment]
Having a template class for the MWS targets (templates.MWS) that was built on the STAR class would certainly work, and I agree it would be a clean way to do it.

**Comment by crockosi** [comment]
I should have been more specific in that last comment:  Unless there are objections, will take David Kirkby's suggestion and implement a templates.MWS class in response to this issue, which includes creating a base STAR class that does things common to all STAR targets.  I will leave alone the current templates.STAR class.  I could also make a templates.FSTD class while I'm at it and factor it the same way, if it would be useful.  But I won't anything about the FSTDs unless there is agreement that I should.

**Comment by moustakas** [comment]
Refactoring along these lines sounds great to me -- there is nothing set in stone the way things were written and there are many places in the code that would benefit from a reorganization / refactorization like this.  Thanks you!

**Comment by sbailey** [comment]
+1 for also creating a separate FSTD class, in particular to get the r-band magnitude range correct by default for standard stars.  See PR #88.  The current STAR(FSTD=True).make_templates() gets the colors right but not the magnitudes unless the user overrides the rmagrange defaults.

**Comment by sbailey** [comment]
Fixed via PR #94
