### ISSUE TITLE
newexp-desi --flavor bgs and bright

### ISSUE THREAD

**Issue by sbailey** [desihub/desisim#71]
Once #70 (add BGS-like templates) is done, add `newexp-desi --flavor bgs` and `bright` options.

`--flavor bgs` would simulate just Bright Galaxy Survey targets, while `bright` would do a mix of BGS and MWS targets based upon the target densities in $DESIMODEL/data/targets/targets.dat .

Use `exptime_bright` from desimodel.io.load_params() for exposure time for flavors `mws`, `bgs`, and `bright`.

**Comment by moustakas** [comment]
I note that that file (targets.dat) doesn't contain any information about MWS, and the BGS numbers are woefully out of date / incorrect.  

A related question: will MWS be applying color cuts to select particular subpopulations?

**Comment by sbailey** [comment]
Placeholder numbers for MWS, BGS have been added to desimodel and PR #92 fixed a bug for newexp-desi --flavor bright.  Closing ticket.
