### ISSUE TITLE
generate canonical brighttime sims

### ISSUE THREAD

**Issue by sbailey** [desihub/desisim#72]
Once #71 is done to enable `newexp-desi --flavor bright`, generate a canonical set of bright time simulations and advertise those for use in future pipeline development (e.g. data challenges).

While we're at it, do the same for an updated set of dark time exposures too.

**Comment by dkirkby** [comment]
Will these bright time simulations use the new scattered moon model in specsim (desihub/specsim#9) ?

**Comment by moustakas** [comment]
Yes, using the lunar model is critical for the BGS and MWS simulations.
