### ISSUE TITLE
basis templates aren't FITS standard compliant, breaking some FITS readers

### ISSUE THREAD

**Issue by sbailey** [desihub/desisim#78]
The elg, lrg, star, and wd basis templates in /project/projectdirs/desi/spectro/templates/basis_templates/v1.1/ aren't FITS-standard compliant (the QSO templates are).  In particular, HDU2 has an extraneous SIMPLE=T second keyword, when BITPIX is supposed to be the second keyword.  These files work with astropy and mrdfits, but cause the more picky cfitsio to fail (and thus fitsio too).

Current code works because astropy.io.fits is our standard fits reader, but the next iteration on templates should fix this as well.

**Comment by moustakas** [comment]
OK, I think this was a pretty easy fix -- just needed to remove the SIMPLE=T keyword.  Will close this when I release the new set of basis templates (<days).
```
import fitsio
wave, hdr = fitsio.read('bgs_templates_v2.0.fits',ext=2,header=True)
print(hdr)
XTENSION= 'IMAGE   '           /Image Extension created by MWRFITS v1.12b
BITPIX  =                  -32 / Number of bits per data pixel
NAXIS   =                    1 / Number of data axes
NAXIS1  =                33281 /
WAVEMIN =              950.000 / minimum wavelength
WAVEMAX =              40673.7 / maximum wavelength
AIRORVAC= 'vac     '           / wavelengths in vacuum (vac) or air
CUNIT1  = 'Angstrom'           / units of wavelength array
PCOUNT  =                    0 /
GCOUNT  =                    1 /
```

**Comment by sbailey** [comment]
For the record, these templates still fail fitsverify due to:
```
=================== HDU 3: Image Exten. ====================
 
*** Error:   PCOUNT is not in record 5 of the header.
*** Error:   GCOUNT is not in record 6 of the header.
```
However, I think that is actually a bug in fitsverify, not in these files themselves.  The [fits standard](https://archive.stsci.edu/fits/fits_standard/node39.html#SECTION00941200000000000000) specifies that PCOUNT and GCOUNT must exist, but is pretty clear that they don't have to be keywords 5 and 6 as fitsverify seems to think.

Closing this ticket as fixed.
