### ISSUE TITLE
Move/merge filters into desiutil

### ISSUE THREAD

**Issue by sbailey** [desihub/desisim#8]
Move filters into desimodel so that desispec doesn't have to depend upon desisim.  Add/move io code to desimodel to read those filters.  If needed, standardize filters into a common format for different telescopes.

For discussion: should basic filter operations (integrate over a filter, calculate a magnitude, ...) also be in desimodel along with the filters, or in desispec?  Having those calculations in desimodel feels a bit like feature creep and a non-intuitive place to look for them, but having them in desispec separated from the filters also seems a bit odd.  The motivation for putting them in desimodel instead of desispec is because some non-spectral code may want to use them, e.g. mock making (paraphrased comment from Peder Norberg, March 2015).  But the association with code for using the filters may be the counter argument.  

Discuss.

**Comment by moustakas** [comment]
I have a somewhat strong preference that the filters and associated code should be in desispec, not in desimodel.  The (light-weight) filters and associated code should go hand-in-hand, full stop.  In addition, desimodel presumably will remain behind the LBNL/svn wall, whereas there's no reason the filters--and the code to work with the filters---should be hidden.  

Two other relevant notes:
1. I checked in (well-documented) ASCII versions of the DECaLS and SDSS filters into desisim/data -- we should be sure we adopt a consistent set.
2. In my branch of desisim there is a class called filter.py which handles the filter convolutions I need for generating mock templates -- eventually this should be eliminated or merged with what Govinda/Stephen wrote in the context of the flux-calibration.

**Comment by moustakas** [comment]
Note https://github.com/desihub/specsim also (independently) handles filter convolutions. Obviously specsim is experiment-agnostic, so we don't want specsim to depend on anything in desiXXX, but this does suggest we might want a lower-level solution to dealing with filters and filter convolutions in general (e.g., redshift-fitting is going to want this, too).

**Comment by sbailey** [comment]
It now seems like desiutil is the right place to put filters and code for the desiXXX magnitude calculations, even if specsim also has this functionality.  desispec, desitarget, desisurvey, and desisim might all depend upon filter and mag calculations.  We (I?) don't want data-oriented packages like desispec depending upon a simulation-oriented package like specsim, even if that results in replicated code.

Related: I'd like to spin off a "desitest" package for the end-to-end integration tests covering target selection, fiber assignment, simulations, and spectro pipeline.  It could also include consistency tests like ensuring that desisim magnitude calculations match specsim calculations.

**Comment by dkirkby** [comment]
I was already planning to refactor `specsim` to remove generic re-usable algorithms, including filter convolutions.  I just created desihub/specsim#16 to track this and welcome all input there.

> We (I?) don't want data-oriented packages like desispec depending upon a simulation-oriented
> package like specsim, even if that results in replicated code.

I think code duplication is the greater evil here, especially since it also involves duplicating unit tests, doc strings, filter curve data files, etc.  However, we should be able to find a way to solve this with suitable packaging, and the result might even be useful to the broader astro community (especially if packaged for the astropy ecosystem).

As a specific proposal for discussion, I suggest that we either:
* make a standalone astropy-affiliated package containing filter curves and related code, or
* add this functionality to the existing [speclite package](http://speclite.readthedocs.org/en/latest/overview.html) and possibly also move it under `desihub` (but keep it non-DESI specific).

**Comment by sbailey** [comment]
If you can wait that long, let's chat about this at the Dec 1 DESI data telecon (this week is internal review, next week is reserved for Survey).  I'm open to moving this into speclite and bringing that in as a dependency, but it would be useful to enumerate ways in which speclite is "lite" in areas that we would rather be more complete/detailed/whatever.

e.g. coadds are another candidate for using from speclite, but the "right" way to do coadds depends upon tradeoffs on speed, covariance tracking, re-diagonalizing, etc.  There doesn't seem to be a one-size-fits-all solution for coadds, and I'm not sure if speclite should (or wants to) support multiple styles of coadds.

**Comment by sbailey** [comment]
In the end, we used the filter/mag code in speclite, as implemented in PR #81.  Closing issue.
