### ISSUE TITLE
Add travis tests of quickgen and quickbrick

### ISSUE THREAD

**Issue by dkirkby** [desihub/desisim#96]
These scripts are currently not tested by travis or included in coverage reports.

I believe the main obstacle is that any test would need to read the following files that currently live in the `desimodel` svn package:
```
Loaded 65000 rows from .../desimodel/data/spectra/spec-sky.dat with args {'format': 'ascii'}
Loaded 65000 rows from .../desimodel/data/spectra/spec-sky-bright.dat with args {'format': 'ascii'}
Loaded 65000 rows from .../desimodel/data/spectra/spec-sky-grey.dat with args {'format': 'ascii'}
Loaded 65000 rows from .../desimodel/data/spectra/ZenithExtinction-KPNO.dat with args {'format': 'ascii'}
Loaded 667 rows from .../desimodel/data/sky/solarspec.txt with args {'format': 'ascii.basic'}
Loaded 4233 rows from .../desimodel/data/specpsf/psf-quicksim.fits with args {'hdu': 'QUICKSIM-R'}
Loaded 22411 rows from .../desimodel/data/throughput/thru-r.fits with args {'hdu': 'THROUGHPUT'}
Loaded 4761 rows from .../desimodel/data/specpsf/psf-quicksim.fits with args {'hdu': 'QUICKSIM-B'}
Loaded 24651 rows from .../desimodel/data/throughput/thru-b.fits with args {'hdu': 'THROUGHPUT'}
Loaded 4799 rows from .../desimodel/data/specpsf/psf-quicksim.fits with args {'hdu': 'QUICKSIM-Z'}
Loaded 25531 rows from .../desimodel/data/throughput/thru-z.fits with args {'hdu': 'THROUGHPUT'}
Loaded 27 rows from .../desimodel/data/throughput/fiberloss-perfect.dat with args {'format': 'ascii'}
Loaded 27 rows from .../desimodel/data/throughput/fiberloss-star.dat with args {'format': 'ascii'}
Loaded 27 rows from .../desimodel/data/throughput/fiberloss-lrg.dat with args {'format': 'ascii'}
Loaded 27 rows from .../desimodel/data/throughput/fiberloss-qso.dat with args {'format': 'ascii'}
Loaded 27 rows from .../desimodel/data/throughput/fiberloss-sky.dat with args {'format': 'ascii'}
Loaded 27 rows from .../desimodel/data/throughput/fiberloss-elg.dat with args {'format': 'ascii'}
Loaded 65000 rows from .../desimodel/data/spectra/spec-ABmag22.0.dat with args {'format': 'ascii'}
```
(The list above was produced by running `quickspecsim -c desi --verbose`.)

Another problem is that `desisim` does not have a formal dependency on `specsim` that I can see.  My guess is that we need to updated `requirements.txt` and `etc/travis_env_common.sh` to fix this.

Finally, new unit tests need to be created that invoke quickgen and quickbrick.  I am not sure how to do this for standalone scripts under `bin/`, but it would be straightforward if we adopt the entrypoints mechanism recommended [here](http://astropy.readthedocs.org/en/latest/development/scripts.html).

**Comment by dkirkby** [comment]
This issue was previously discussed on #93.

**Comment by sbailey** [comment]
desisim/etc/travis_env_common.sh installs a lightweight version of desimodel (branch test-0.4) that is used for testing.  It also installs https://github.com/desihub/desisim-testdata to get lightweight input templates needed for desisim testing.  i.e. everything except specsim itself should already be installed in the current travis config.  If something is missing from desimodel branch test-0.4, we should create a new lightweight testing branch with whatever is needed.  See desimodel.trim.trim_data(indir, outdir) for a tool to do this.

quickgen and quickbrick should be refactored into library functions that are easily testable, with lightweight wrappers around them (but not console scripts! : )
