### ISSUE TITLE
review objtype / flavor usage

### ISSUE THREAD

**Issue by sbailey** [desihub/desisim#97]
Our usage of flavor and objtypes is getting a little out of hand in desispec.  ELG, LRG, QSO seemed straightforward enough, but we are starting to get things like MWS vs. MWS_STAR, STD vs. STD_FSTAR vs. FSTD, etc.  This issue is a placeholder to think about the big picture of how this should work and do some cleanup.

**Comment by moustakas** [comment]
With data now in-hand, I think our choices are basically now baked in. Closing with no action.
